### ISSUE TITLE
Can't run Pyznap

### ISSUE THREAD

**Issue by netpro25** [yboetz/pyznap#10]
Hello,

After a fresh install using the provided instructions (on github README) I'm seeing the following error:

```
(env) root@pgh2:~# pyznap
Traceback (most recent call last):
  File "/root/env/bin/pyznap", line 7, in <module>
    from pyznap.main import main
  File "/root/env/lib/python3.4/site-packages/pyznap/main.py", line 18, in <module>
    from .utils import read_config, create_config
  File "/root/env/lib/python3.4/site-packages/pyznap/utils.py", line 15, in <module>
    from .process import run
  File "/root/env/lib/python3.4/site-packages/pyznap/process.py", line 44, in <module>
    class CompletedProcess(sp.CompletedProcess):
AttributeError: 'module' object has no attribute 'CompletedProcess'
```

Am I missing a package? I tried installing this on two seperate machines with the same result.

**Comment by yboetz** [comment]
Hm that is very strange. I wonder if that has anything to do with python 3.4, I only use 3.5 & 3.6. I'll have to test on 3.4 myself, I'll let you know when I know more.

**Comment by netpro25** [comment]
Yboetz,

You are correct it's related to python 3.4. I've installed 3.6.6 via pyenv using the following directions and it worked!

https://gist.github.com/jaydenkieran/75b2bbc32b5b70c4fdfb161ecdb6daa2

**Comment by yboetz** [comment]
Yes, I also just saw that in python 3.4 the subprocess module does not have the CompletedProcess class, that only came in 3.5. That's why the code couldn't run. I will change the readme to python 3.5+ only. Thanks!
