### ISSUE TITLE
ModuleNotFoundError: No module named 'pyznap'

### ISSUE THREAD

**Issue by jedi-nz** [yboetz/pyznap#102]
Hi Yannick,

After upgrading from Ubuntu 20.04 to Ubuntu 22.04 I am now getting this error:

`root@ubuntuzfs:~# pyznap snap`
`Traceback (most recent call last):`
  `File "/root/.local/bin/pyznap", line 5, in <module>`
    `from pyznap.main import main`
`ModuleNotFoundError: No module named 'pyznap'`

Do you know how to fix it? I have removed all comments from the config file.

Thank you for your help.

**Comment by yboetz** [comment]
Have you tried reinstalling pyznap? I just tried on a new Ubuntu 22.04 install and I didn't get any error when running pyznap.

**Comment by jedi-nz** [comment]
Yay pyznap working again :-)
Thank you Yannick!

**Comment by jedi-nz** [comment]
Same error when upgrading to Ubuntu 24.04

Solved it by coping the pyznap directory from /usr/local/lib/python3.10/dist-packages to the /usr/local/lib/python3.12/dist-packages

Thanks to [https://github.com/yboetz/pyznap/issues/106](url)

Putting this here so I know what to do when I upgrade to 26.04 cos I won't remember.
