### ISSUE TITLE
Get rid of the Makefile

### ISSUE THREAD

**Issue by Duffyx** [yboetz/pyznap#13]
I'm trying to port your program to FreeBSD altough the Makefile is casuing problems.
As the install targets are not default; calling pip commands etc.
Can you make it so that you only rely on setup.py and setup.cfg?

Two nice examples are:
https://github.com/certbot/certbot
https://github.com/sivel/speedtest-cli/

For the python porting toolchain you can take a look at this:
https://github.com/freebsd/freebsd-ports/blob/master/Mk/Uses/python.mk

Thanks

**Comment by Duffyx** [comment]
You can find my in progress work here: https://github.com/Duffyx/pyznap
I error out with the following:
![image](https://user-images.githubusercontent.com/32487486/46583408-bf488800-ca56-11e8-8e93-9b2a42612021.png)

**Comment by yboetz** [comment]
You don't need the Makefile. It's just for convenience, but if you use the command `pip install pyznap` the Makefile is not used. It's just as a shorthand for `make release` to automatically upload to pypi.

i don't really know FreeBSD, so I don't really know what the problem is here.

**Comment by Duffyx** [comment]
Somehow the FreeBSD make framework picks up the Makefile of you and fails because of it. 
I"ll check with FreeBSD mail list on this issue.

**Comment by Duffyx** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232161
Fixed it. Was a stupid typo in my Makefile LOL .
