### ISSUE TITLE
Invalid id_rsa file

### ISSUE THREAD

**Issue by HarmoniaUniversum** [yboetz/pyznap#16]
I have been at it all day, and I finally installed pyznap in virtualenv. When I run it, I get the error message.

> ERROR: /root/.ssh/id_rsa is not a valid ssh key file...

I am trying to replicate a pool.

I can ssh manually between the two machines, even using keys. The weird thing is no matter what setting I change, the error message doesn't change. For example, if I misspell the path on purpose, say "/rwaoot/.ssh/id_rsa"

I have even regenerated the keys.

Any insights? Would be greatly appreciated.

Thank you!

**Comment by yboetz** [comment]
Hi

You will get the `/root/.ssh/id_rsa is not a valid ssh key file...` error message if the file `/root/.ssh/id_rsa` does not exist. Did you create the keys as your root user? Does the file exist?

Do you let pyznap run as your root user? pyznap checks if the file exists with `os.path.isfile`. This will also return false if pyznap does not have permissions to access the file. So if you don't let pyznap run as root user then any file in `/root/` will not be accessible.

**Comment by HarmoniaUniversum** [comment]
I created the keys as root, the file /root/.ssh/id_rsa exists, and I am running pyznap as root. I am stumped. 

see my whoami output  below

```
(pyznap) root@fileserver01:/home/frank/virtualenvironment/pyznap/bin# whoami
root
```
and the listing under /root/.ssh/

```
root@fileserver02:~/.ssh# ls
authorized_keys  config  id_rsa  id_rsa.pub  known_hosts
```

**Comment by yboetz** [comment]
Just to check the basics, your python virtualenv is python 3.5+?

If yes, could you open a python interpreter (as root) and do the following:

    import os
    os.path.isfile('/root/.ssh/id_rsa')

You should only see this error message if the file does not exist or if permissions are wrong. But it seems both of those are not the case, so I'm a bit stumped as well.

Can you also show me your config?

**Comment by HarmoniaUniversum** [comment]
I didn't realise that it's checking the source machine's key! The python test gave false, so I generated the keys on the source machine and that problem seems gone. 

Now the error message I get is 

```
Nov 05 15:44:57 INFO: Starting pyznap...
Nov 05 15:44:57 INFO: Sending snapshots...
Traceback (most recent call last):
  File "/home/frank/virtualenvironment/pyznap/bin/pyznap", line 11, in <module>
    sys.exit(main())
  File "/home/frank/virtualenvironment/pyznap/lib/python3.5/site-packages/pyznap/main.py", line 103, in main
    send_config(config)
  File "/home/frank/virtualenvironment/pyznap/lib/python3.5/site-packages/pyznap/send.py", line 212, in send_config
    zfs.open(dest_name, ssh=ssh)
  File "/home/frank/virtualenvironment/pyznap/lib/python3.5/site-packages/pyznap/pyzfs.py", line 85, in open
    type = findprops(name, ssh=ssh, max_depth=0, props=['type'])[name]['type'][0]
KeyError: 'fileserver02pool/datas   # Specify ssh destination'

```

below is my config file (only the part I've edited and uncommented from the original)

```
[datas/datas]
# hourly = 24
# snap = yes
# clean = yes
dest = ssh:22:root@192.168.2.27:fs02pool/datas   # Specify ssh destination
dest_keys = /root/.ssh/id_rsa    # Provide key for ssh login. If none given, look in home dir
```

if I run the command directly without using the config file, here's what I get. (I need to do a full stream not a snapshot ... I am basically migrating the pool to a new server and planning to keep and use the original for backup, and your tool seems like the best solution for my needs. )

```
(pyznap) root@fileserver01:/home/frank/virtualenvironment/pyznap/bin# pyznap send -s datas/datas -d ssh:22:root@192.168.2.27:fs02pool/datas
Nov 05 16:06:10 INFO: Starting pyznap...
Nov 05 16:06:10 INFO: Sending snapshots...
Nov 05 16:06:11 ERROR: No snapshots on dataserver/dataserver, cannot send...
Nov 05 16:06:11 INFO: Finished successfully...
```

Thanks very much for your help btw!

**Comment by yboetz** [comment]
Ah yes, you need to give your source machine access to the destination machine by specifying a key on the source. How did the manual ssh work though if you didn't have a key on the source machine?

For your other error:
Remove the comments after your config entries, so e.g. only write `dest_keys = /root/.ssh/id_rsa` without the comment after. Lines starting with a `#` will be ignored, but any `#` within a line is treated as part of the line. 

zfs send/receive always works an snapshots. You can only send snapshots, so there needs to be a snapshot on your source that you can send. A snapshot is an immutable read only copy of the filesystem at a certain point in time. So if you take a snapshot and don't add any files after that, you will fully replicate your whole filesystem.

Either let pyznap create snapshots for you or manually create a (recursive) snapshot on your source, then you will be able to send it. I would advise you to use the snapshot functionality of pyznap in any case, it's one of the best feature of zfs and has no drawbacks that I can think of.

**Comment by HarmoniaUniversum** [comment]
Re manual connection: I did create and send the key to the destination after I realised the issue.

As you can see, I am a newbie :-) ... I didn't realise the comments after matter! Especially since there's no end of statement character.  A little thinking would have gone a long way here, lol ... but live and learn!

Thanks also for the explanation on snapshots.

It is now working and I cannot tell you how excited I am! Thanks a mil!

**Comment by HarmoniaUniversum** [comment]
You inspired me to, I did a bunch of that today! A lot of what I was going to seek other solutions for is already part of ZFS' feature set. Also, you inspired me to look into Python. It seems very elegant. 

The snapshot I took yesterday was with zfs directly as opposed to pyznap, because I couldn't get it to work, but I am pretty sure I just need to tweak the config file now that I know more. So thanks again!

**Comment by HarmoniaUniversum** [comment]
I forgot to ask something. Today I was reading that there is a new ZFS send feature where you can resume a send is something happens before it's complete. I happen to have experienced this exact need because I am transferring ~5T over LAN and yesterday a router rebooted spontaneously when it was at 50G and was shocked to realise I have to start afresh. See this thread .. https://goo.gl/MNs1eT

So my question is have you implemented this feature in pyznap or if not is it easy?

**Comment by yboetz** [comment]
No, that is not implemented yet. Resumeable send/receive was introduced in ZOL (zfs on linux) in version 0.7.x. I'm still on 0.6.5, so resumeable send/recv was not on my priority list and I haven't had time to implement it yet. It shouldn't be too hard though, but it is a feature I cannot use anyway, so I haven't prioritized it.

Normally this shouldn't be too big of a problem, as after the initial sync pyznap will do incremental updates. Also, if you take regular snapshots and a zfs send gets canceled, all already transferred snapshots  will remain on the destination. So there you will also not have to start over fresh again. 

If you need automatic resumeable send/recv you could have a look at [syncoid](https://github.com/jimsalterjrs/sanoid).

**Comment by yboetz** [comment]
If everything is working I'll close this for now. If anything else is not working you can open another issue.

**Comment by HarmoniaUniversum** [comment]
All is working perfectly thanks! Just about to complete my first 4.6TB transfer. Thanks for everything!
