### ISSUE TITLE
pv progress more than 100%

### ISSUE THREAD

**Issue by Duffyx** [yboetz/pyznap#19]
Hi,

The pv feature is nice! Altough it shows a progress bar thats more than 100% when complete?

![image](https://user-images.githubusercontent.com/32487486/48312757-e6ddc380-e5b3-11e8-894a-2d37ef284c05.png)

**Comment by yboetz** [comment]
That has to do with the snapshot size reporting in ZFS. I use the command `zfs send -nP ...` to get the stream size. The reporting is very inaccurate though for small snapshot sizes. So if the snapshot is almost empty it shows something like 1-2KB, but the size might be a bit more or less. PV then calculates the progress according to that size it gets from ZFS. If that is inaccurate though then it will show more or less than 100%.

**Comment by Duffyx** [comment]
Alrighty, thanks!
