### ISSUE TITLE
Cron Snap or Send? does not remount some pools after finish

### ISSUE THREAD

**Issue by backamblock** [yboetz/pyznap#20]
Hi there,
i just installed and configured pyznap, great tool btw!, and the question came to mind.
My cronjob looks like this:
*/15 * * * *   root    { /path/to/pyznap snap ; /path/to/pyznap send ; } >> /var/log/pyznap.log
is it really necessary to do both snap and send when "dest" is another local HDD?

And then there is also some strange thing happening..
i make a new ZFS Subvol zpool-backup/rpool which is the "dest=" in pyznap.conf
before pyznap runs i still have the .zfs folder with "share" and "snapshot" folders in it.
after pyznaps first run, the entire .zfs folder is missing.. 

what am i missing here?! on the source pool the .zfs dir is present.
Also on another pool, which i backup to zpool-backup/nvme this folder is persistent and does not get deleted

Please help :smile: 

edit: seems like it can not mount the dest rpool again after finishing the snapshot.. ok i can live with that..
but it does not do that to other backup destinations.
do you have any idea why that is?

**Comment by backamblock** [comment]
this is on Proxmox where rpool is the installation pool
so the default is:
rpool
rpool/ROOT
rpool/ROOT/pve-1 #which is the local filesystem root
rpool/data  #where Proxmox stores VMs and stuff by default

when i set only rpool/ROOT/pve-1 to be backed up, .zfs folder persists on the dest and i can view the snapshots, but when i choose the parent it gets deleted. but it exists on the source..

**Comment by backamblock** [comment]
> Is it missing or just not showing? Just go to the mountpoint and try `cd .zfs` and see if you can enter the folder. Usually the .zfs folder should not show, but you should always be able to enter it.

> I would guess that when you backup your pool you copy the mountpoints. Your original pool is then still mounted, so you cannot mount your backup pool in the same location. You can get the mountpoint of all filesystems with `sudo zfs list -o name,mountpoint`.

pool                                            mount
rpool                                           /rpool
zpool-6tb/backup/rpool               /zpool-6tb/backup/rpool

the mountpoint seems to be correct, and when i mount it manually it works fine, but then pyznap throws an error that it can not unmount it. "target busy"
after a reboot i can cd into the backup/rpool/.zfs and the snapshots are present.
when pyznap runs it is unmounted again. 

anyway, it is not that big of a deal, when i really need to restore a snapshot it is an easy workaround :)
so far pyznap works silently in the background and maybe saves some future day :+1:

**Comment by yboetz** [comment]
Can you post your pyznap config?

**Comment by backamblock** [comment]
[rpool]
frequent = 4
hourly = 6
daily = 0
weekly = 0
monthly = 0
yearly = 0
snap = yes
clean = yes
dest = zpool-6tb/backup/rpool

[zpool-nvme]
frequent = 4
hourly = 6
daily = 0
weekly = 0
monthly = 0
yearly = 0
snap = yes
clean = yes
dest = zpool-6tb/backup/nvme

[zpool-6tb/nas]
frequent = 4
hourly = 6
daily = 0
weekly = 0
monthly = 0
yearly = 0
snap = yes
clean = yes
dest = zpool-6tb/backup/nas

[zpool-6tb/backup]
frequent = 8
hourly = 48
daily = 14
weekly = 8
monthly = 6
yearly = 0
snap = no
clean = yes

the cron to this is:
*/15 * * * *    root    { /usr/local/bin/pyznap snap ; /usr/local/bin/pyznap send ; } >> /zpool-6tb/backup/log/pyznap.log

**Comment by yboetz** [comment]
Hm strange, I cannot see anything wrong with this. Two things (that have nothing to do with your problem): 

  - In the config for your backup you specify it to keep 14 daily, 8 weekly, etc... snapshots. But on none of your original pools you take daily, weekly, ... snapshots, so there will never be any daily, weekly,... snapshots on your backup. If you want to have daily, weekly, ... snapshots on your backup then you have to take the same backups on your original pools.
  - Backing up `zpool-6tb/nas` to `zpool-6tb/backup/nas` does not really give any benefit, does it? It is still on the same pool and if the pool fails then both original data and backup are gone.

Apart from that everything seems fine with your config. I don't know why it would throw an error and why it would want to unmount to begin with... At what point does it give the error? Can you show the line in the logfile (with a few before and after)?
