### ISSUE TITLE
Output only errors to be send via email by cron

### ISSUE THREAD

**Issue by backamblock** [yboetz/pyznap#21]
To follow up on the issue about errors and logging #8 
is there a way to output only Errors?
I run the cron every 15 minutes and looking for errors manually would be pretty exhausting.
thanks

**Comment by yboetz** [comment]
No there is not. But printing only the errors of a logfile is very easy, just do

    grep ERROR /var/log/pyznap.log

You might even be able to add this to your cron, as in 

    pyznap snap | grep ERROR > /var/log/pyznap.log

though I have not tested if this works in cron.

You could also set up something like [logcheck](http://logcheck.org/) to automatically scan your logfiles for certain keywords like `ERROR` and send you an email whenever it finds something.
