### ISSUE TITLE
compression during send ?

### ISSUE THREAD

**Issue by svennd** [yboetz/pyznap#23]
Perhaps I missed it, but can I set compression "on" during the zfs send to the backup location ? (from tests it looked like this speeds up the transfer significantly here.) Is there an option to do this ? (I tried checking in the code, and realized my python is bad 😄

**Comment by yboetz** [comment]
Unfortunately no, not yet. I've wanted to implement this for a while now, but didn't have the time so far. At some point I want to have a lzop/gzip compression option during send/recv, but atm there is no compression.

**Comment by svennd** [comment]
Thanks for the quick answer; Am I wrong to assume you are using zfs send ? Cause this has support for compressed file systems (-c or --compressed). In my case the FS and backup FS are using lz4 compression, so there is no need for ZFS to decrypt them before sending.

Anyways, thanks for this nice tool, it works nicely !

**Comment by yboetz** [comment]
It uses zfs send/recv. I was not aware that there is an option for sending a compressed stream. Can you send me a link to the zfs docs about that? Couldn't find anything.

I also use lz4 compression on my datasets, would obviously be nice to just send them as it is.

**Comment by svennd** [comment]
I could not find it online either (perhaps its a new feature); its in the manual for zfs (man zfs \zfs send)

```   
    -c, --compressed
           Generate a more compact stream by using compressed WRITE records for blocks which
           are compressed on disk and in memory (see the compression property for details).
           If the lz4_compress feature is active on the sending system, then the receiving
           system must have that feature enabled as well.  If the large_blocks feature is
           enabled on the sending system but the -L option is not supplied in conjunction
           with -c, then the data will be decompressed before sending so it can be split
           into smaller block sizes.
```
You can see the difference by streaming to an .img, the size is allot smaller for the compressed version.

The patch can be seen here : https://github.com/zfsonlinux/zfs/commit/a7004725d0ad52fa005c29f68ce55273f11d95ac

Perhaps make it an optional flag ?

**Comment by yboetz** [comment]
Hm that sounds interesting. Though what happens if the source filesystem is lz4 compressed but the dest filesystem is gzip compressed? Most of my backup filesystems are using gzip, while my data pools are lz4.

I will have to look into this.

**Comment by yboetz** [comment]
I just release v1.2.0, which finally has compression support. Supported at the moment are `none`, `lzop`, `lz4`, `gzip`, `pigz`, `bzip2` and `xz`. Speedup when transferring highly compressable datasets are quite substantial :).

**Comment by svennd** [comment]
great will try 1!
