### ISSUE TITLE
send snapshots cleaning

### ISSUE THREAD

**Issue by svennd** [yboetz/pyznap#25]
What would be the easiest way to clean up "old snapshots" on a backup location ?  Can I use pyznap on the remote location to clean up ?

**Comment by yboetz** [comment]
Yes, that is one of the intended use of pyznap. You don't need to run pyznap on the remote though, you can simply make an entry for your remote location with the cleanup policy, e.g.:

    [ssh:22:root@backupserver]
    key = /root/.ssh/id_rsa
    hourly = 24
    daily = 14
    weekly = 8
    clean = yes

This will then log into your remote machine and clean up all snapshots.

**Comment by svennd** [comment]
thx yboetz, that was unclear to me; thanks !
