### ISSUE TITLE
Noops when executed from cron

### ISSUE THREAD

**Issue by mikelococo** [yboetz/pyznap#28]
I feel like this is likely to be more of a support request than a true bug report, but I'm out of ideas for how to investigate further.

Summary
=======

When executed from a normal root shell, pyznap behaves as expected. When executed from cron, log output confirms that pyznap does in fact execute... but it always decides incorrectly that no snapshots should be taken.

Steps to reproduce
==============

Stand up an Ubuntu 16.04.6 LTS instance, install python3 and python3-pip. Use pip3 to install pyznap.

Create `/etc/cron.d/pyznap_cron` with the following contents:
`0 * * * * root /usr/local/bin/pyznap --config /etc/pyznap/pyznap.conf snap | /usr/bin/logger -t pyznap-snap`

After running `pyznap setup` as root, edit `/etc/pyznap/pyznap.conf` as follows:
```
# Primary pools containing live data, snapshot them but don't retain very long
[zfs-pool/files-lan]
hourly = 24
daily = 1
weekly = 1
monthly = 1
snap = yes
clean = yes
dest = backup-pool/zfs-pool-files-lan-backups

[zfs-pool/container-volumes]
hourly = 24                          
daily = 1
weekly = 1
monthly = 1
snap = yes                          
clean = yes                        
dest = backup-pool/zfs-pool-container-volumes-backups

## Destination Pools, don't take snapshots, only receive them. Longer retention
[backup-pool/zfs-pool-files-lan-backups]
hourly = 48
daily = 7
weekly = 4
monthly = 12
snap = no
clean = yes

[backup-pool/zfs-pool-container-volumes-backups]
hourly = 48
daily = 7
weekly = 4
monthly = 12
snap = no
clean = yes

## A couple of directories in the backup-pool that I rsync stuff to from non-zfs filesystems.
# No hourlies, but otherwise snapshot and retain as if they were a destination.
[backup-pool/manual-backups]
daily = 7
weekly = 4
monthly = 12
snap = yes
clean = yes

[backup-pool/srvr-backup]
daily = 7
weekly = 4
monthly = 12
snap = yes
clean = yes
```

Now wait for cron to kick in and observe the behavior of pyznap.

Expected Behavior
==============

1. Pyznap runs every hour on the 0th minute.
2. The output of Pyznap is logged in /var/log/syslog, tagged with pyznap-snap
3. Pyznap generates at least one snapshot in every run. Generally more due to multiple filesystems and periodicities.

Actual Behavior
============

Pyznap DOES run every hour on the 0th minute.

I can verify this because it DOES log output in /var/log/syslog:
```
Mar  7 19:00:01 srvr CRON[1614]: (root) CMD (/usr/local/bin/pyznap --config /etc/pyznap/pyznap.conf snap | /usr/bin/logger -t pyznap-snap)
Mar  7 19:00:01 srvr pyznap-snap: Mar 07 19:00:01 INFO: Starting pyznap...
Mar  7 19:00:01 srvr pyznap-snap: Mar 07 19:00:01 INFO: Taking snapshots...
```

The above is the complete output. Note that pyznap takes no action and generates no snapshots. This is the part that violates my expectation. I believe that pyznap should determine that a snapshot is necessary on every run.

As a test, if I now run the exact same command from a root shell (manually, outside of cron, but still piping output to `logger`), having made no config edits since the cron run, I see that pysnap does decide now that snapshots SHOULD be made... as verified by this output in /var/log/syslog:
```
Mar  7 19:36:25 srvr pyznap-snap: Mar 07 19:36:25 INFO: Starting pyznap...
Mar  7 19:36:25 srvr pyznap-snap: Mar 07 19:36:25 INFO: Taking snapshots...
Mar  7 19:36:25 srvr pyznap-snap: Mar 07 19:36:25 INFO: Taking snapshot zfs-pool/container-volumes@pyznap_2019-03-07_19:36:25_hourly...
Mar  7 19:36:25 srvr pyznap-snap: Mar 07 19:36:25 INFO: Taking snapshot zfs-pool/files-lan@pyznap_2019-03-07_19:36:25_hourly...
Mar  7 19:36:25 srvr pyznap-snap: Mar 07 19:36:25 INFO: Cleaning snapshots...
Mar  7 19:36:25 srvr pyznap-snap: Mar 07 19:36:25 INFO: Finished successfully...
Mar  7 19:36:25 srvr pyznap-snap: 
```

This is not just a case of a single missed run. Pyznap has been running every hour for 10 hours today prior to this test, with no config edits at all during this time. Pyznap has generated no snapshots during that period at all, when it should have been creating hourlies for two of the filesystems.

Additional Analysis
==============

Note the timestamps, these runs were taken within the same hour. The previous snapshots for these two filesystems are about 9h 28m old, and were created by a pyznap run from the shell as I was manually testing. Pyznap has run every hour during this period, and has issued the same log output each time and declined to produce snapshots each time. In fact, neither `pyznap snap` nor `pyznap send` have ever taken any action from cron on this system (though logs confirm they each run when expected), though they work fine from the shell.

Here's the output of `zfs list` after the most recent successful run from a shell at 19:36 (except for the missing snapshots from 10:00-19:00 today it's pretty much as I expect, some random snapshots from manual runs as I was testing/setting up, plenty of free space)...
```
root@srvr:~# zfs list
NAME                                                                               USED  AVAIL  REFER  MOUNTPOINT
backup-pool                                                                       5.08T  1.95T   128K  /backup-pool
backup-pool/manual-backups                                                        66.5G  1.95T  66.5G  /backup-pool/manual-backups
backup-pool/manual-backups@pyznap_2019-03-07_10:08:27_monthly                         0      -  66.5G  -
backup-pool/manual-backups@pyznap_2019-03-07_10:08:28_weekly                          0      -  66.5G  -
backup-pool/manual-backups@pyznap_2019-03-07_10:08:29_daily                           0      -  66.5G  -
backup-pool/srvr-backup                                                           2.58T  1.95T  2.58T  /backup-pool/srvr-backup
backup-pool/srvr-backup@pyznap_2019-03-07_10:08:31_monthly                            0      -  2.58T  -
backup-pool/srvr-backup@pyznap_2019-03-07_10:08:32_weekly                             0      -  2.58T  -
backup-pool/srvr-backup@pyznap_2019-03-07_10:08:33_daily                              0      -  2.58T  -
backup-pool/zfs-pool-container-volumes-backups                                    21.6G  1.95T  21.6G  /backup-pool/zfs-pool-container-volumes-backups
backup-pool/zfs-pool-container-volumes-backups@pyznap_2019-03-06_22:53:11_hourly      0      -  21.6G  -
backup-pool/zfs-pool-files-lan-backups                                            2.41T  1.95T  2.41T  /backup-pool/zfs-pool-files-lan-backups
backup-pool/zfs-pool-files-lan-backups@pyznap_2019-03-06_22:53:11_hourly              0      -  2.41T  -
zfs-pool                                                                          2.47T  2.80T  38.1G  /zfs-pool
zfs-pool/container-volumes                                                        21.7G  2.80T  21.6G  /zfs-pool/container-volumes
zfs-pool/container-volumes@pyznap_2019-03-06_22:53:11_hourly                      55.2M      -  21.6G  -
zfs-pool/container-volumes@pyznap_2019-03-07_09:19:20_hourly                        92K      -  21.6G  -
zfs-pool/container-volumes@pyznap_2019-03-07_10:08:34_monthly                         0      -  21.6G  -
zfs-pool/container-volumes@pyznap_2019-03-07_10:08:36_weekly                          0      -  21.6G  -
zfs-pool/container-volumes@pyznap_2019-03-07_10:08:38_daily                           0      -  21.6G  -
zfs-pool/container-volumes@pyznap_2019-03-07_10:08:39_hourly                          0      -  21.6G  -
zfs-pool/container-volumes@pyznap_2019-03-07_19:36:25_hourly                          0      -  21.6G  -
zfs-pool/files-lan                                                                2.41T  2.80T  2.41T  /zfs-pool/files-lan
zfs-pool/files-lan@pyznap_2019-03-06_22:53:11_hourly                              96.5M      -  2.41T  -
zfs-pool/files-lan@pyznap_2019-03-07_09:19:21_hourly                                  0      -  2.41T  -
zfs-pool/files-lan@pyznap_2019-03-07_10:08:39_monthly                                 0      -  2.41T  -
zfs-pool/files-lan@pyznap_2019-03-07_10:08:39_weekly                                  0      -  2.41T  -
zfs-pool/files-lan@pyznap_2019-03-07_10:08:39_daily                                   0      -  2.41T  -
zfs-pool/files-lan@pyznap_2019-03-07_10:08:39_hourly                                  0      -  2.41T  -
zfs-pool/files-lan@pyznap_2019-03-07_19:36:25_hourly                                  0      -  2.41T  -
```

Apologies for the giant wall of text in this report, but I'm a bit flummoxed and wanted to give you the best chance of being able to debug it in a single viewing. My first inclination was that I had failed to correctly configure the cron job... but pyznap is so clearly executing on the hour every hour as expected... it's just not taking the expected actions during each run. I don't see any way to get debug output, and am not sure where to investigate next.

From the shell, it's been super neato so far. I love the ease of the pip-install, and the sanoid configuration approach is blissfully simple.

**Comment by yboetz** [comment]
This is very strange. The syslog output when running with cron suggests that pyznaps just crashes at some point, because it should always finish log messages with `Finished successfully...` before exiting. The config and cron looks fine as well, I have a very similar setup and use cron just as you. Could you maybe test it without logger, as this is the only thing different from my setup. Though I wouldn't know how this would be a problem... Maybe just try once a cron like this:

     0 * * * * root /usr/local/bin/pyznap --config /etc/pyznap/pyznap.conf snap >> /tmp/pyznap.log

(Btw, you can omit the `--config /etc/pyznap/pyznap.conf` if you use the standard path `/etc/pyznap/pyznap.conf`for your config. pyznap checks for that file automatically, you only need to specify it if its a different filename/directory).

Apart from that I'll have to make some tests myself, this is something I never encountered before :).

**Comment by yboetz** [comment]
Could you also check if there are any defunct pyznap processes? Maybe pyznap hanged somewhere and all those cronjobs are still running. Just check with something like:

    ps auxf | grep -i pyznap

or maybe also

    ps auxf | grep -i cron

**Comment by mikelococo** [comment]
1. "it should always finish log messages with `Finished successfully...`" <- That's interesting. I hadn't realized.
2. Here's my new cron line, based on your suggestions (I had started without explicitly specifying the config, but when troubleshooting I was trying to eliminate implicit things that might not behave as I expect): `0 * * * * /usr/local/bin/pyznap snap >> /var/log/pyznap_snap.log`
3. I also know enough python to hack up my install with extra debugging messages. If it's truly crashing out in the middle of the run, I think I'll have a better idea about where it's blowing up, which looks likely to be somewhere in take_config or some call further down the stack from there.
4. I don't believe there are defunct pyznap or cron processes lying about:

```
  % ps auxf | grep -i pyznap
mike     19737  0.0  0.0  14224   960 pts/2    S+   10:31   0:00      \_ grep --color -i pyznap

  % ps auxf | grep -i cron
root      4247  0.0  0.0  29008  2328 ?        Ss   Mar05   0:00 /usr/sbin/cron -f
mike     19759  0.0  0.0  14224   972 pts/2    S+   10:31   0:00      \_ grep --color -i cron
```

I believe that cron -f is the expected daemon started by the init system.

Will respond again when I have some info from the next run.

**Comment by yboetz** [comment]
You can also change the cron to `* * * * *` temporarily to see what you get and check if you get any defunct processes. It seems like it crashes somewhere in the middle though, very weird that it has absolutely no error messages though. 

There are actually some more verbose log messages that you could see by invoking `logger.setLevel(logging.DEBUG)` in the pyznap main file. I only use these when debugging, so there is no flag to set this from the outside (yet). Also it's not much, it would be helpful if you set some extra debugging messages throughout the code yourself.

**Comment by mikelococo** [comment]
I'm juggling some other stuff, so having a break between test runs is not so bad. But yeah, if I get some time to focus on this tonight I'll bump the cron frequency.

I added WAY more messages than were there before. Basically before and after almost anything that looked like it might possibly fail. Just to zero in on the last line of code that got executed successfully.

**Comment by mikelococo** [comment]
Ok, I have this pinned down to a failing line. Here's my hacked up log output, which I think you'll be able to infer where I added most of this stuff by the text in them, which pretty closely tracks the source code:

```
Mar 08 11:46:01 INFO: Hacky - Parsing args...
Mar 08 11:46:01 INFO: Hacky - Parsed args...
Mar 08 11:46:01 INFO: Starting pyznap...
Mar 08 11:46:01 INFO: Hacky - Snap or Send is in args.command...
Mar 08 11:46:01 INFO: Hacky - Successfully read config...
Mar 08 11:46:01 INFO: Hacky - We have take or full...
Mar 08 11:46:01 INFO: Taking snapshots...
Mar 08 11:46:01 INFO: Hacky - Not using ssh...
Mar 08 11:46:01 INFO: Hacky - Attempting to zfs.find children...
Mar 08 11:46:01 INFO: Hacky - Entering ZFS find
Mar 08 11:46:01 INFO: Hacky - max_depth is none
Mar 08 11:46:01 INFO: Hacky - Successfully processed max_depth
Mar 08 11:46:01 INFO: Hacky - Have type
Mar 08 11:46:01 INFO: Hacky - Successfully processed type
Mar 08 11:46:01 INFO: Hacky - Have path
Mar 08 11:46:01 INFO: Hacky - Successfully processed path
Mar 08 11:46:01 INFO: ['zfs', 'list', '-H', '-r', '-t', 'filesystem,volume', '-o', 'name,type', 'backup-pool/manual-backups']
Mar 08 11:46:01 INFO: Hacky - Executing zfs.find cmd...
```
And here's the hacked up source code in the `find` function of `pyzfs.py`:
```
    logger.info(cmd)
    logger.info('Hacky - Executing zfs.find cmd...')
    out = check_output(cmd, ssh=ssh)
    logger.info('Hacky - Suceeded at zfs.find cmd...')
```

Note that the find log statement is never emitted. We appear to terminate during check_output. I haven't tried yet to wrap this in a try/except or anything, preferring to get you the info on where the failure is happening before digging deeper.

**Comment by mikelococo** [comment]
From the shell, I think I'm seeing this works fine... though I don't know all those flags off the top of my head to see if the output is exactly what we want:
```
% sudo zfs list -H -r -t 'filesystem,volume' -o 'name,type' backup-pool/manual-backups
backup-pool/manual-backups      filesystem
```

**Comment by yboetz** [comment]
Thanks for the very detailed logs. Very weird... The output you get from the shell is exactly what you want. But it seems that it just crashes when calling check_output. To narrow it down even further, could you add some hacky lines in the `run` function in `process.py`? As you are not running it over ssh, you only have to add some lines in the first part after `with sp.Popen(*popenargs, **kwargs) as process:` Would be great to print out stdout and stderr there, to see if he returns something or just crashes completely immediately after entering the Popen.

**Comment by mikelococo** [comment]
Oh, sure. I misread check_output as being stdlib or I would have instrumented it the first time. It looks like `with sp.Popen(...)` blows up:

```
Mar 08 12:53:01 INFO: Hacky - Parsing args...
Mar 08 12:53:01 INFO: Hacky - Parsed args...
Mar 08 12:53:01 INFO: Starting pyznap...
Mar 08 12:53:01 INFO: Hacky - Snap or Send is in args.command...
Mar 08 12:53:01 INFO: Hacky - Successfully read config...
Mar 08 12:53:01 INFO: Hacky - We have take or full...
Mar 08 12:53:01 INFO: Taking snapshots...
Mar 08 12:53:01 INFO: Hacky - Not using ssh...
Mar 08 12:53:01 INFO: Hacky - Attempting to zfs.find children...
Mar 08 12:53:01 INFO: Hacky - Entering ZFS find
Mar 08 12:53:01 INFO: Hacky - max_depth is none
Mar 08 12:53:01 INFO: Hacky - Appended -r to cmd
Mar 08 12:53:01 INFO: Hacky - Successfully processed max_depth
Mar 08 12:53:01 INFO: Hacky - Have type
Mar 08 12:53:01 INFO: Hacky - Successfully processed type
Mar 08 12:53:01 INFO: Hacky - Have path
Mar 08 12:53:01 INFO: Hacky - Successfully processed path
Mar 08 12:53:01 INFO: ['zfs', 'list', '-H', '-r', '-t', 'filesystem,volume', '-o', 'name,type', 'backup-pool/manual-backups']
Mar 08 12:53:01 INFO: Hacky - Executing zfs.find cmd...
Mar 08 12:53:01 INFO: Hacky - Entering run method
Mar 08 12:53:01 INFO: Hacky - SSH is none
```

And the hacked up code:

```
    logger.info('Hacky - Entering run method')
    if ssh is None:
        logger.info('Hacky - SSH is none')
        with sp.Popen(*popenargs, **kwargs) as process:
            logger.info('Hacky - popened')
```

Note that the logger message inside the `with` never executes, so I don't think we get far enough to be able to see stdout/stderr.

**Comment by yboetz** [comment]
Hm I googled a bit about Popen and cron. Do you have the path set in your cron file? The command python executes just calls `zfs`, so if no path is set it wouldn't know to look for this in `/sbin/zfs`.

My cron file has these additional lines:

    SHELL=/bin/sh
    PATH=/root/.virtualenvs/pyznap/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

**Comment by mikelococo** [comment]
Ok, I fixed up my mistakes and they did not affect the output after all. As I suspected before, it's failing to popen, so I can't get stdout or stderr from the failing case:

```
... omitted irrelevant bits...
Mar 08 13:04:02 INFO: Hacky - Executing zfs.find cmd...
Mar 08 13:04:02 INFO: Hacky - Entering run method
Mar 08 13:04:02 INFO: Hacky - SSH is none
```

Here's the hacked up code (note that the popened log line is never emitted):

```
    if ssh is None:
        logger.info('Hacky - SSH is none')
        with sp.Popen(*popenargs, **kwargs) as process:
            logger.info('Hacky - popened')
```

Here's the result of a run from the shell where popen works, I don't log stdout/stderr but you can see it cranks through everything as expected, getting a 0 retcode and returning to the caller. Execution continues on and with my hacked up code creates lots and lots of messages and take snapshots, all as you'd expect.

```
... omitting stuff...
Mar 08 13:04:49 INFO: Hacky - Executing zfs.find cmd...
Mar 08 13:04:49 INFO: Hacky - Entering run method
Mar 08 13:04:49 INFO: Hacky - SSH is none
Mar 08 13:04:49 INFO: Hacky - popened
Mar 08 13:04:49 INFO: Hacky - communicated
Mar 08 13:04:49 INFO: Hacky - about to fetch returncode
Mar 08 13:04:49 INFO: 0
Mar 08 13:04:49 INFO: Should we raise a calledprocesserror?
Mar 08 13:04:49 INFO: About to return
Mar 08 13:04:49 INFO: Hacky - Suceeded at zfs.find cmd...
... omitting more stuff, the run succeeds...
```

**Comment by mikelococo** [comment]
I'll double check the path thing, I'll bet that's it.

**Comment by mikelococo** [comment]
Oof, how embarrassing, that was it. I've now changed my /etc/cron.d/pyznap contents to be:

```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

4 * * * * root /usr/local/bin/pyznap --config /etc/pyznap/pyznap.conf snap 2>&1 | logger -t pyznap-snap
38 2 * * * root /usr/local/bin/pyznap --config /etc/pyznap/pyznap.conf send 2>&1 | logger -t pyznap-send
```

Notable changes include setting SHELL and PATH, and also critically redirecting both STDOUT and STDERR with `2>&1`. If you redirect stderr, then your logfiles when you encounter this look like this:

```
Mar  8 15:04:01 srvr cron[4247]: (*system*pyznap_cron) RELOAD (/etc/cron.d/pyznap_cron)
Mar  8 15:04:01 srvr CRON[10900]: (root) CMD (/usr/local/bin/pyznap --config /etc/pyznap/pyznap.conf snap 2>&1 | logger -t pyznap-snap )
Mar  8 15:04:01 srvr pyznap-snap: Mar 08 15:04:01 INFO: Starting pyznap...
Mar  8 15:04:01 srvr pyznap-snap: Mar 08 15:04:01 INFO: Taking snapshots...
Mar  8 15:04:01 srvr pyznap-snap: Traceback (most recent call last):
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/local/bin/pyznap", line 10, in <module>
Mar  8 15:04:01 srvr pyznap-snap:     sys.exit(main())
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/local/lib/python3.5/dist-packages/pyznap/main.py", line 120, in main
Mar  8 15:04:01 srvr pyznap-snap:     return _main()
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/local/lib/python3.5/dist-packages/pyznap/main.py", line 89, in _main
Mar  8 15:04:01 srvr pyznap-snap:     take_config(config)
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/local/lib/python3.5/dist-packages/pyznap/take.py", line 146, in take_config
Mar  8 15:04:01 srvr pyznap-snap:     children = zfs.find(path=fsname, types=['filesystem', 'volume'], ssh=ssh)
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/local/lib/python3.5/dist-packages/pyznap/pyzfs.py", line 40, in find
Mar  8 15:04:01 srvr pyznap-snap:     out = check_output(cmd, ssh=ssh)
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/local/lib/python3.5/dist-packages/pyznap/process.py", line 110, in check_output
Mar  8 15:04:01 srvr pyznap-snap:     universal_newlines=True, ssh=ssh, **kwargs)
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/local/lib/python3.5/dist-packages/pyznap/process.py", line 148, in run
Mar  8 15:04:01 srvr pyznap-snap:     with sp.Popen(*popenargs, **kwargs) as process:
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
Mar  8 15:04:01 srvr pyznap-snap:     restore_signals, start_new_session)
Mar  8 15:04:01 srvr pyznap-snap:   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
Mar  8 15:04:01 srvr pyznap-snap:     raise child_exception_type(errno_num, err_msg)
Mar  8 15:04:01 srvr pyznap-snap: FileNotFoundError: [Errno 2] No such file or directory: 'zfs'
```

The stack trace makes it perfectly clear what's going on. I noticed we weren't seeing stack traces, but I didn't stop to think about why and just tried to debug around it.

I think maybe a readme update will make folks less likely to encounter this in the future. Maybe something like:

> and let pyznap run regularly by adding the following lines
> ```
> SHELL=/bin/sh
> PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
> */15 * * * *   root    /path/to/pyznap snap 2>&1 >> /var/log/pyznap.log
> ```
> This will run pyznap every quarter hour to take and delete snapshots. 'frequent' snapshots can be taken up to once per minute, so adjust your cronjob accordingly. `2>&1` ensures that both STDOUT and STDERR are redirected to your log file so you'll see both healthy log messages from STDOUT and also exception messages that are only printed to STDERR and that can be critical to troubleshooting failures. The PATH and SHELL lines ensure that pyznap can find external executables like `zpool` and `zfs` in standard locations on your system, you may need to modify the precise path depending on where various binaries are installed.

Thanks so much for your help debugging this. Pyznap is looking super awesome and I can't wait to see it get snapping automatically now.

**Comment by yboetz** [comment]
Uff, I did not think of stderr redirect either, even though I have it in my cronjobs... :)

Glad I could help and that it works now. I'll update the readme accordingly. Maybe I should also update `FileNotFoundError` for a graceful exit there, but that might also just bloat the code...

**Comment by mikelococo** [comment]
Friendly error messages and graceful exits are never bad, but the stack trace is pretty readable as-is in my opinion. Plus I'm sure there are other uncaught exceptions somewhere, so the bigger win is probably getting the userbase broadly logging stderr so they're equipped to handle all those situations. Thanks again!

**Comment by yboetz** [comment]
Added more info to the readme just now. Thanks for the suggestion.
