### ISSUE TITLE
Pull snapshots from remote source to local destination

### ISSUE THREAD

**Issue by ShaRose** [yboetz/pyznap#30]
According to the example configuration, you can create snapshots on a remote host, but not send them to another destination.

Would it be possible to add the option to 'pull down' snapshots from the remote host to the local one after doing the snapshots?

**Comment by yboetz** [comment]
At the moment this is a limitation of the way I have implemented the send/recv functions. I've wanted to change this for a while now, such that pulling snapshots and other things are possible. I've started working on this (see develop branch), but I cannot give you any date on when this will be available, as I'm quite busy at the moment...

**Comment by testbird** [comment]
Hi, this sounds very good to only have to configure pyznap on one or two backup hosts with limited ssh access to initiate the transfers to external storage on the servers.

**Comment by testbird** [comment]
Maybe a helpful python package package for pulling to non-zfs storage: https://github.com/omry/snapdump

**Comment by yboetz** [comment]
This functionality was added in v1.3.0, you can now send from local to local, local to remote, remote to local and remote to remote. Note though that remote to remote is not direct but goes via the local machine. So you can now in your policy specify

    [ssh::user@host:tank/data]
    key = /root/.ssh/id_rsa
    dest = backup/data
    compress = lz4

to pull data from the remote `user@host:tank/data` to your local pool `backup/data`. Similarly in the cli you can use

    pyznap send -s ssh::user@host:tank/data -d backup/data -c lz4

**Comment by testbird** [comment]
Cool, very useful, looking forward to a central backup configuration. Thank you!
