### ISSUE TITLE
Send exclusion

### ISSUE THREAD

**Issue by ShaRose** [yboetz/pyznap#31]
When sending snapshots to a destination, it seems that pyznap is looping each dataset and sending them one at a time: Would it be possible to add a check to not send some filesystems (even if they are snapshotted) by using either configuration, or using a user property?

**Comment by yboetz** [comment]
Should be possible by simply adding a regex check before sending, but again I cannot guarantee any date if/when this will be available :).

**Comment by yboetz** [comment]
This was added in release v1.4.0. You can now exclude datasets using [Unix shell-type wildcards](https://docs.python.org/3/library/fnmatch.html). A sample config might look like this:

    [rpool]
    dest = backup/rpool, tank/rpool
    exclude = rpool/data rpool/home/*/documents rpool/home/user1, rpool/home*
