### ISSUE TITLE
znap error to run setup on Ubuntu 18.04 server

### ISSUE THREAD

**Issue by l2fl2f** [yboetz/pyznap#32]
Dear,

After installation via pip as root
`$ apt install python-pip
$ pip --proxy http://172.30.3.39:3128 install pyznap`

`$ pyznap setup -p /etc/pyznap
Traceback (most recent call last):
  File "/usr/local/bin/pyznap", line 7, in <module>
    from pyznap.main import main
  File "/usr/local/lib/python2.7/dist-packages/pyznap/main.py", line 18, in <module>
    from .utils import read_config, create_config
  File "/usr/local/lib/python2.7/dist-packages/pyznap/utils.py", line 14, in <module>
    from subprocess import Popen, PIPE, TimeoutExpired, CalledProcessError
ImportError: cannot import name TimeoutExpired
`

uname -a: `Linux lxc850 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

lsb_release -a: `
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
`

Thx

**Comment by yboetz** [comment]
pyznap needs python 3.5+, so you need to install it with `pip3`. If you use the system python installation, I would advise to use the `--user` flag, i.e.

    $ pip3 --user install pyznap

**Comment by l2fl2f** [comment]
thx, I will try next Monday :) have a good week-end

**Comment by l2fl2f** [comment]
Thx, everything is working :), ok I can't wait to Monday morning...
