### ISSUE TITLE
send/recv encrypted snaps

### ISSUE THREAD

**Issue by testbird** [yboetz/pyznap#34]
ZFS 0.8 has been released and has hit the PPA

https://github.com/yboetz/pyznap/issues/3#issuecomment-354594297:
>  'raw' send/recv will only be necessary once encryption is available, but I will be very interested in that once it makes its way into Ubuntu LTS. Implementing it would be quite easy I think, just one more flag '-w', which would be trivial.

**Comment by DragonQ** [comment]
Yep this feature would be great. I'm on ZoL 0.8.0 and want to start using encrypted datasets but since I use pyznap to send backups to my secondary NAS I'll probably wait until pyznap supports this feature. It should hopefully only require the adding of an extra config option and then an extra switch in the zfs send/recv command.

**Comment by yboetz** [comment]
I will try to work on this in the coming month, though again no promise on any date :).

**Comment by recklessnl** [comment]
Has there been any progress on this? Looking forward to this feature.

**Comment by yboetz** [comment]
No sorry, no progress on this yet. I haven't looked into native encryption yet, though as I already said, this should not be too hard. I'll look into this next.

**Comment by yboetz** [comment]
Sorry about the long wait. I implemented the `-c` flag in pyznap that should work for both encrypted and compressed datasets. I could only test it for compressed datasets on my machines atm, would any of you be able to test it for encrypted send/recv? I made a beta release [v1.5.0-beta](https://github.com/yboetz/pyznap/releases/tag/v1.5.0-beta) with all the changes.

**Comment by testbird** [comment]
Sorry, I can't test currently.

**Comment by DragonQ** [comment]
> 
> Sorry about the long wait. I implemented the `-c` flag in pyznap that should work for both encrypted and compressed datasets. I could only test it for compressed datasets on my machines atm, would any of you be able to test it for encrypted send/recv? I made a beta release [v1.5.0-beta](https://github.com/yboetz/pyznap/releases/tag/v1.5.0-beta) with all the changes.

I'm confused, looking through the code it seems as if the -w switch is needed, but you reckon it's -c?

**Comment by yboetz** [comment]
Hm I might have misunderstood the documentation then. I thought the `-c` implies the `-w` flag for encrypted datasets, but it seems to be vise versa, the `-w` flag implies `-c` for unencrypted datasets. I'll change this and make a new release.

**Comment by recklessnl** [comment]
Have there been more tests with this? Is this all working correctly in the new beta release?

**Comment by yboetz** [comment]
Sorry, I just updated the new beta release now. I need to find a way to test this on my side, as I'm still on ZOL 0.6 and 0.7.

**Comment by yboetz** [comment]
Ok I just tested the new v1.5.0-beta2 release in a VM with zol 0.8. It seems to work for me, though I don't have much experience with encrypted datasets. The simple tests I tried worked, though maybe it would be better if someone with real usecases tries it out before merging it into master.

**Comment by fmwolf** [comment]
I tested out the behavior of sending encrypted datasets on v1.5.0-beta2. One thing I notice is that I am unable to send snapshots without the encryption key loaded on the backup (receiving server). One of the nice things about sending encrypted zfs datasets is that you do not need the key to be loaded on the receiving server. This is helpful if you do not necessarily trust the security of the receiving server.

For example, using the standard zfs send/receive tools I am able to send a dataset without the key loaded on the receiving server successfully via the following syntax:
`$ sudo zfs send -w -I poolname/filesystem@snap1 poolname/filesystem@snap2 | pv | ssh user@server2 zfs receive poolname/filesystem`

When I attempt to send snapshots on an encrypted dataset via pyznap, I get this message regarding the key not being loaded:
```
$ sudo pyznap send -w
Mar 11 01:06:35 INFO: Starting pyznap... 
Mar 11 01:06:35 INFO: Sending snapshots...
Mar 11 01:06:40 INFO: Updating user@server2:poolname/filesystem with recent snapshot poolname/filesystem@snap2 (~901.4K)...
Mar 11 01:06:40 ERROR: Error while sending to user@server2:poolname/filesystem: cannot receive incremental stream: inherited key must be loaded...
Mar 11 01:06:40 INFO: Finished successfully...
```

When I load the key on the receiving server I am able to update it via pyznap.

```
$ sudo pyznap send -w
Mar 11 01:07:17 INFO: Starting pyznap...
Mar 11 01:07:17 INFO: Sending snapshots...
Mar 11 01:07:21 INFO: Updating user@server2:poolname/filesystem with recent snapshot poolname/filesystem@snap2 (~901.4K)...
Mar 11 01:07:46 INFO: user@server2:poolname/filesystem is up to date...
Mar 11 01:07:46 INFO: Finished successfully...
```

Thank you very much for your work on this helpful project.

**Comment by yboetz** [comment]
Hi, thanks for testing! The flag `-w` only works if you send directly with the full command:

    pyznap send -w -s source/dataset -d dest/dataset

If you call `pyznap send` without the `-s` and `-d` flags, then it looks for the config file and sends according to the policy there. If you didn't specify raw send there, then it will overwrite the `-w` flag and thus try to send normally, which is not possible if the key is loaded. Can you add the entry `raw_send = yes` to your config entry and try again? And you can also try to send as in the command above.

**Comment by fmwolf** [comment]
Adding the `raw_send = yes` to my config file works perfectly for my use case! Thank you so much for your help!

**Comment by yboetz** [comment]
Thanks a lot for testing the feature! I'll test it again on my side then release a new version.

**Comment by recklessnl** [comment]
Thanks for updating this @yboetz. Would be helpful to update the main documentation readme for pyznap too to explain how to do the encrypted sends, as things can get confusing fast.

**Comment by yboetz** [comment]
I updated the readme in the `develop` branch, though I will check again if all the info is there.

**Comment by yboetz** [comment]
This is now in release v1.5.0.

**Comment by DragonQ** [comment]
FYI, I've tested this with an encrypted dataset. I sent the initial dataset with a `zfs send -w -p` parameters (to preserve properties and send raw), then did some pyznap snaps & sends. I then deleted the original dataset and restored it by sending the backed up one from the remote machine. I was able to decrypt the restored dataset and access the data as expected.

Nice work. :)
