### ISSUE TITLE
"pyznap send" fails with "Host key verification failed" errors

### ISSUE THREAD

**Issue by DragonQ** [yboetz/pyznap#40]
Ever since 16th July (i.e. immediately after the new versions were released and installed on my machine), my `pyznap send` job fails every night with the error:

`ERROR: Error while connecting to root@backup-nas: Host key verification failed....`

My config file has these lines for every dataset:

`dest = ssh:22:root@backup-nas:backups/<dataset>`
`dest_keys = /home/user/.ssh/id_rsa`

Nothing has changed in terms of configuration, and I can still SSH successfully to the backup-nas machine using the following command from the terminal (which is what I would expect pyznap to do):

`ssh root@backup-nas -i /home/user/.ssh/id_rsa`

Sounds like a bug with the new SSH implementation?

**Comment by yboetz** [comment]
Hm sounds like it. I've tested it with multiple machines and I didn't encounter any problems so far. In your config file, is the `@backup-nas` a full address or is it an alias that you have defined in your `.ssh/config` file?

**Comment by DragonQ** [comment]
`backup-nas` is defined in /etc/hosts as an IP address. There is nothing in `/root/.ssh/` except `authorized_keys` and `known_hosts`, which is why I'm using another user's keys. `/home/user/.ssh/config` doesn't exist either.

I suppose I could work around this by adding a `/root/.ssh/config` file defining the use of the user's key for `backup-nas`, but that defeats the purpose of the `dest_keys` line in the `pyznap.conf` file.

**Comment by yboetz** [comment]
I just tried out to set an IP in my `/etc/hosts` file and then use `pyznap send` using that host, seemed to work without problem. Also, you should not have to add something to your `.ssh/config` file, the pyznap config entries should be enough.

The `Host key verification failed` error would indicate some problem with your `known_hosts` file, though as you said you can connect without problem using `ssh root@backup-nas -i /home/user/.ssh/id_rsa`....

**Comment by yboetz** [comment]
Try this: Log in as root and then do

    ssh root@backup-nas -i /home/user/.ssh/id_rsa

There should be a message to add verify the authenticity of host 'backup-nas'. Type yes and then disconnect. After that try to run `pyznap send` and check if it still fails.

**Comment by DragonQ** [comment]
Yep, that did the trick, thanks. Not sure why it required a fresh host verification when it was working fine before though. :/

**Comment by yboetz** [comment]
When you are logging in as your normal user and connect over ssh, it will add the host to the file `/home/user/.ssh/known_hosts`. pyznap is run as root though, so when connecting via ssh it will check `/root/.ssh/known_hosts` and will not find `backup-nas` in there. Usually it will then query to add the host to the known_hosts, but when you run it via cron you don't get that query. If you run it manually you would also have gotten that query and after that it will also work in cron. 

Before v1.2.0 I used paramiko (python ssh module) to set up the ssh connections, and I guess it checked multiple `known_hosts` files until it found an entry, or even ignored it alltogether. I will look into this.

**Comment by yboetz** [comment]
I just checked it. In the old code I had the known_hosts policy to

    ssh.set_missing_host_key_policy(pm.WarningPolicy())

This means that paramiko would have warned if a host key is missing, but would connect anyway. Did you not see a warning in your pyznap logfile in the old version?

**Comment by DragonQ** [comment]
> 
> 
> I just checked it. In the old code I had the known_hosts policy set to
> 
> ```
> ssh.set_missing_host_key_policy(pm.WarningPolicy())
> ```
> 
> This means that paramiko would have warned if a host key is missing, but would connect anyway. Did you not see a warning in your pyznap logfile in the old version?
Nope, no warnings in the pyznap log file from before 16th July.

**Comment by yboetz** [comment]
Ok, then I must have disabled these log messages. The new behavior thus is not to connect if the host is not in the `known_hosts` file. Either you manually connect to the host once before you start pyznap (using the correct user), or you manually run pyznap once (not in cron), s.t. it queries you about the host.
