### ISSUE TITLE
Remote dataset become unmounted after pyznap send

### ISSUE THREAD

**Issue by surfchris** [yboetz/pyznap#44]
Not sure if it is intentional or not, but the destination datasets on remote machine become unmounted after every pyznap send. Are there any settings I can use to avoid that? 

Source is on Proxmox and destination is on a FreeNAS. Source datasets are always mounted, and the destination datasets can be remounted if I reboot FreeNAS (or done manually I guess). My config for testing purposes looks like this:

[testpool]
frequent = 30
snap = yes
clean = yes
dest = ssh:22:root@192.168.1.14:WD10P/test
dest_keys = /home/user/.ssh/id_rsa
compress = gzip

Thanks for making such a awesome piece of software!

**Comment by yboetz** [comment]
The same just came up in #43, I think I misunderstood/misused the `-u` flag for `zfs receive`. Though in my backup system the datasets always stay mounted, though I don't know why... I'll look into it.

**Comment by surfchris** [comment]
Ok. Sounds good! I didn't read #43, but see now that it's the same. Just closing this then. Thanks.
