### ISSUE TITLE
How best to configure send/receive?

### ISSUE THREAD

**Issue by cfnz** [yboetz/pyznap#46]
First up, thanks for pyznap :-)... just figuring out how best to use it... so this is more a question than an issue, or maybe the issue is I am not sure how to proceed based on the documentation... I am new to ZFS, so new to pyznap and zfs send/receive. 

Say I have a dataset I want to replicate to a different server. I want a number of backups (snapshots) on the source server and a number of backups on the destination server. For simplicity, say on the source server I have daily = 5 and hourly = 24 in the pyznap.conf file.

I have noticed that you don't actually need pyznap on the destination to receive snapshots, so I assume it uses zfs directly.

On the source I call "pyznap snap" regularly and my datasets get snapshoted as expected.

Calling "pyznap send" sends all the snapshots to the backup server, it does not delete old snapshots (i.e. older than 5 days/24 hours) off of the backup server. 

I also read somewhere that you could setup the backup server to store say 20 days of snapshots and no hourlies.

So how should I set up the source and destination in this case?

Should the source only send the latest snapshot and then the destination does its own snapshots? i.e. Is it more resource intensive to send lots of snapshots (e.g. all the hourly ones each day) that might not even get used on the destination (e.g. the destination might not keep hourlies at all, only dailies)

Or 

Should I continue to just use "pyznap send" to send the all the daily snapshots over to the destination and configure pyznap.conf to keep the number of snapshots I want on the destination and perhaps set snap = no on the destination? Is that the main purpose for snap = no, i.e. to tidy up snapshots on a destination based on settings in the config file.

Does my question even make sense?
Thanks for any feedback. Also, if this is not the right place to ask such questions, happy to be redirected.

**Comment by yboetz** [comment]
> I have noticed that you don't actually need pyznap on the destination to receive snapshots, so I assume it uses zfs directly.

Yes, it uses zfs commands, so you don't need to run pyznap on your dest.

> Should the source only send the latest snapshot and then the destination does its own snapshots?

You absolutely cannot do this. If the destination does its own snapshots, there will be a mismatch of snapshots and you will not be able to send snapshots from your source anymore. You will then have to destroy your data on dest (or at least the wrong snapshots) and do a full sync again. It's not (noticeably) more resource intensive to send more snapshots, even when they are not used on the dest. 

> Should I continue to just use "pyznap send" to send the all the daily snapshots over to the destination and configure pyznap.conf to keep the number of snapshots I want on the destination and perhaps set snap = no on the destination? Is that the main purpose for snap = no, i.e. to tidy up snapshots on a destination based on settings in the config file.

This is what you should do. The `snap = no` means just don't take any snapshots -- on the dest this is necessary.

So you configure your source to take regular snapshots and then send them to your remote destination. You then also configure pyznap to regularly clean snapshots on your dest. Here's a sample config for that, similar to the setup I have:

[source/data]
hourly = 24
daily = 5
snap = yes
clean = yes
dest = destination/data

[destination/data]
daily = 20
snap = no
clean = yes

You then run `pyznap snap --take` regularly, and once per day you can call `pyznap snap --clean` and `pyznap send`. This will take regular snapshots, clean them once per day and send them to your dest. On the dest all hourly snapshots will be deleted when you use `--clean`, so they are not necessary, but it's not possible to only transfer dailys (at least not with pyznap). 

One point to watch out for: To do incremental backups, there needs to be a common snapshot between source and dest. So if you only keep 5 dailys on your source, then absolutely need to do your backup more than every 5 days. As soon as the last of those 5 daily snapshots is deleted on your source, there will be no common snapshots with your dest and you will have to destroy and do a full sync again.

**Comment by cfnz** [comment]
OK, thanks for this. And especially for both source/destination configs.

I was thinking that as the destination got updated I could do snapshots on the changes to it (e.g. snapshot the destination before and zfs receive and again after)... but sounds like that is not how it works... I need to ensure I have a common snapshot and go from there...

So I believe I am on the right track now :-)
Thanks again.
