### ISSUE TITLE
Remote snapshots (on FreeNAS) are not deleted according to rule...

### ISSUE THREAD

**Issue by surfchris** [yboetz/pyznap#47]
Hi again, I'm sorry for making yet another issue. 

Source is Proxmox/Debian and remote is FreeNAS/FreeBSD. Dataset "small" on source to dataset "test" on remote. My pyznap.conf:
```
[small]
frequent = 5
snap = yes
clean = yes
dest = ssh:22:root@192.168.1.84:System/test
dest_keys = /home/user/.ssh/id_rsa
compress = lz4
```
When running Pyznap snap and Pyznap send (run in serial), only the snapshots on source get deleted per the rule. I tried different combinations of zvol and dataset, and it seems to be unrelated to that this time. I do however suspect that it could have something to do with the remote being FreeBSD. What are the commands you use for snapshot cleanup on remote? (I don't know Python, otherwise I would have looked myself).

Thanks.

**Comment by yboetz** [comment]
pyznap does not automatically clean up the remote dataset, you have to specify a separate entry in your policy, i.e.:

    [ssh:22:root@192.168.1.84:System/test]
    key = /home/user/.ssh/id_rsa
    frequent = 24
    clean = yes

Then whenever you call `pyznap snap` it will delete old snapshots on your remote. You can also just call `pyznap snap --clean` to only clean snapshots, without taking new ones. Most of the time I run first `pyznap send` and then `pyznap snap --clean` to send to my remote and then clean up old snapshots there.

**Comment by surfchris** [comment]
That worked perfectly! Awesome! Thank you.
