### ISSUE TITLE
How do you control when snapshots are taken

### ISSUE THREAD

**Issue by gnordli** [yboetz/pyznap#49]
Hi 
Right now with my home brew scripts I schedule snapshots at night for VMs and the file system datasets are taken hourly during business hours.  

I replicate file system datasets during the day, but the VMs are all synced at night.  Can I configure that with pyznap? 

Also, can I configure the snapshot name?    

Thanks,
Geoff

**Comment by yboetz** [comment]
You can simply create a second config file for the VMs and specify the nightly snapshots + send/recv in that file. Then create another cronjob with `pyznap --config=/etc/pyznap/other-config.conf snap` or `pyznap --config=/etc/pyznap/other-config.conf send` to specify when you want to take snapshots and sync them.

The snapshot names are not configurable.

**Comment by gnordli** [comment]
That makes sense. 
Also, I see that the windows previous versions are working with the current snap names.  That was my reason to change the names. https://github.com/yboetz/pyznap/issues/41
thanks!!
Geoff
