### ISSUE TITLE
python3.6 required?

### ISSUE THREAD

**Issue by bleomycin** [yboetz/pyznap#5]
Is python3.6 absolutely required? I'm running a proxmox host which has a debian 9 stretch base. Debian does not have a python3.6 package, 3.5 is the latest. Thanks!

**Comment by yboetz** [comment]
Actually it should run with any python 3.x, I didn't use any features from 3.6. On my server I run Ubuntu 16.04 with python 3.5.2 and it runs perfectly.

**Comment by bleomycin** [comment]
Awesome, thank you for the excellent software! I just wanted to make sure before running in case of some unexpected behavior.

**Comment by yboetz** [comment]
No problem, glad you can use it!
