### ISSUE TITLE
Email if issue?

### ISSUE THREAD

**Issue by killmasta93** [yboetz/pyznap#52]
Hi,
I was wondering if its possible to get an email alert if there is an issue? of the snapshot ?

Thank you

**Comment by yboetz** [comment]
No, pyznap doesn't have any email alerts. You can easily get an email alert though by grepping the logfile/output, i.e. something like this:

    pyznap snap | grep 'ERROR' && mail -s "pyznap error" user@example.com

This should then send an email whenever there is an "ERROR" in the output. Even better might be to have a small bash script that checks the logfile after pyznap finishes and then sends you the output if there are any warnings/errors.

**Comment by killmasta93** [comment]
Thanks for the reply that did the trick i added this to the cronjob
```

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

50 18 * * *   root     pyznap --config /media/pyznap.conf snap | grep 'ERROR' && mail -s "pyznap error" mail@mydomain.com


```
