### ISSUE TITLE
syntax error at /usr/sbin/sanoid line 1406, near "unlink"

### ISSUE THREAD

**Issue by florian-obradovic** [yboetz/pyznap#53]
Hey,
i just installed sanoid on Ubuntu 18.04 but i get this error on execution
`sanoid
syntax error at /usr/sbin/sanoid line 1406, near "unlink"
Execution of /usr/sbin/sanoid aborted due to compilation errors.`

any hints what I am missing?
Regards, Flo

**Comment by yboetz** [comment]
That you're running sanoid and this is the pyznap repo :)?

**Comment by florian-obradovic** [comment]
oh my gosh, to stupid. 
can you please delete this issue, thx...
