### ISSUE TITLE
Sending Data set though SSH

### ISSUE THREAD

**Issue by killmasta93** [yboetz/pyznap#54]
Hi,
So currently the snapshots working great with no issue, but now im trying to replace pve-zsync as it does not have compression and its a hassle when i try to send data sets an another site though WAN.
so in the .conf
This is what i have 

```
[rpool/data/vm-107-disk-1]
frequent = 30
snap = yes
clean = yes
dest = ssh:22:root@192.168.3.249:rpool/data
dest_keys = /root/.ssh/id_rsa
compress = gzip
```
so my question when i run 

` pyznap --config /media/pyznap.conf send`

should it not send also the disk and the snapshot? as i only see that it sends the snapshot

Thank you

**Comment by yboetz** [comment]
This config sends the dataset `rpool/data/vm-107-disk-1` to the dataset `rpool/data` at `root@192.168.3.249`, including all snapshots. Be aware though that the filesystem `rpool/data` might be unmounted after sending, so you have to mount it again to see it and all files.

**Comment by killmasta93** [comment]
thanks for the reply, thats what i was curious about not sure what you mean unmounted?
when i send the data set i see on the 192.168.3.249 the snapshot but not the disk

**Comment by yboetz** [comment]
On your dest, do `zfs get mounted,mountpoint rpool/data`. You should see that it is not mounted. If so, do `zfs mount rpool/data` and go to the mountpoint and you should see all your data.

**Comment by killmasta93** [comment]
Thanks for the reply this is what i got 

```
root@prometheus26:~# zfs get mounted,mountpoint rpool/data
NAME        PROPERTY    VALUE       SOURCE
rpool/data  mounted     -           -
rpool/data  mountpoint  -           -
root@prometheus26:~#  zfs mount rpool/data
cannot open 'rpool/data': operation not applicable to datasets of this type
```

**Comment by yboetz** [comment]
Hm is this a zvol then? I don't know if you can mount a zvol... But if you see the snapshots there and see the data on there (with `zfs get used rpool/data`), then everything is as it should, no?

**Comment by killmasta93** [comment]
currently using proxmox but is it normal that it unmounts it? somewhat odd, but it seems that its still unmounted 

```
root@prometheus26:~# zfs get used rpool/data
NAME        PROPERTY  VALUE  SOURCE
rpool/data  used      7.98G  -

i go to another proxmox server and it shows this

```
root@prometheus2:~# zfs get mounted,mountpoint rpool/data
NAME        PROPERTY    VALUE        SOURCE
rpool/data  mounted     yes          -
rpool/data  mountpoint  /rpool/data  default
```

```

**Comment by yboetz** [comment]
Then simply mount it by setting a mountpoint, `zfs set mountpoint=/rpool/data rpool/data` and then use `zfs mount rpool/data`. 

pyznap unmounts datasets for sending atm, maybe I can change that at some point. Removing the flag that unmounts resulted in errors though, so I left it in for now.

**Comment by killmasta93** [comment]
thanks for the reply very odd this issue 

```
root@prometheus26:~# zfs set mountpoint=/rpool/data rpool/data
cannot set property for 'rpool/data': 'mountpoint' does not apply to datasets of this type
```

as for the errors not sure as pve-zsync and sanoid does not unmount the remote location but i really like pyznap as its real easy to configure and works real good

**Comment by yboetz** [comment]
Can you do a `zfs get all rpool/data/vm-107-disk-1` and `zfs get all rpool/data`, as well as `zfs list -t snap -r rpool/data/vm-107-disk-1` and `zfs list -t snap -r rpool/data`?

**Comment by killmasta93** [comment]
Thanks for the reply, well what i did delete the dataset and recreated it and fixed the issue but the unmount part is pretty delicate for me as i run vms

**Comment by yboetz** [comment]
It only unmounts the receiving dataset, so that should not be a problem. I also have a lot of LXD containers on zfs that I regularly backup to multiple remote dests, and it never causes any problem.

**Comment by killmasta93** [comment]
Hi, i wanted to comeback to this, to see if i can replace pve-zync with pyznap though ssh, as i recall when i ran pyznap though ssh it unmounts on the remote site?

**Comment by yboetz** [comment]
Yes it does unmount on the remote site. If that is a problem for your workflow then I guess it makes sense to keep using pve-zync?

**Comment by killmasta93** [comment]
true but i like more pyznap because of its compression and more versatile
