### ISSUE TITLE
no common snapshots: what next?

### ISSUE THREAD

**Issue by rbrewer123** [yboetz/pyznap#57]
I've been using pyznap for a while, but one of my offsite backups got stale and now pyznap is giving me the "no common snapshots" error.  I'd rather not blow away the existing snapshots on the backup drive.  What is my next step to tell pyznap to do a full backup anyway?

**Comment by yboetz** [comment]
pyznap cannot do a full backup if there are existing snapshots that do not match the snapshots on the source. To do a full backup you either need to delete all snapshots on the backup dataset, or send to a different dataset. You could also rename your old dataset and create a new one with the same name, then pyznap can start a new full backup on that while you keep the old snapshots in another dataset.

**Comment by rbrewer123** [comment]
Thanks, that's very helpful. 

To anyone following along, I chose the last option: renaming my "backup" dataset to a "backup-archived" variant, creating a new "backup" dataset, and rerunning pyznap, which did a full backup to that.
