### ISSUE TITLE
Option to have the pyznap log output in json

### ISSUE THREAD

**Issue by maireanu** [yboetz/pyznap#61]
If it possible to have the output of the pyznap in json format

**Comment by yboetz** [comment]
What kind of output would you want in json format? I don't think that is something I'll implement in the near future, lots of other features I would like to work on and not that much time...

**Comment by maireanu** [comment]
it will be nice to have the output of the logging in a structured format in order to be easly parsed and send the logs to a monitoring system

**Comment by yboetz** [comment]
You'll have to parse the text log for the moment, I don't plan to change the log output in the near future.

**Comment by maireanu** [comment]
Not neccesary anymore
