### ISSUE TITLE
Clean-up the snapshot source and estination

### ISSUE THREAD

**Issue by maireanu** [yboetz/pyznap#62]
It is possible to clean up the snapshots form the destionation also.

For example the fallowing scenario :
1. we are making a snapshot on on VM ( this is already posibile )
2. send the snapshots to a destination VM ( this is already posible )
3. clean the snapshots on source ( this is already posibile )
4. clean the snapshots on destination  also ( not possible yet )

**Comment by yboetz** [comment]
It is possible, just have a policy entry for your destination, something like this:

    [data]
    hourly = 24
    snap = yes
    clean = yes
    dest = ssh::root@example.com:backup
    
    [ssh::root@example.com:backup]
    hourly = 48
    clean = yes

**Comment by maireanu** [comment]
Understood thank you :)

**Comment by maireanu** [comment]
You can close the issue then
