### ISSUE TITLE
odd number of size on dest?

### ISSUE THREAD

**Issue by killmasta93** [yboetz/pyznap#63]
Hi,
I was wondering if someone could clear up for me how come the disks from the rpool is different size then from the dest?

```
rpool/data/vm-100-disk-0       9.32G  1.15T  6.62G  -
rpool/data/vm-101-disk-0        198G  1.15T   196G  -
rpool/data/vm-102-disk-0       7.43G  1.15T  7.19G  -
rpool/data/vm-103-disk-0       5.95G  1.15T  5.93G  -
rpool/data/vm-103-state-clean   729M  1.15T   729M  -
rpool/data/vm-106-disk-0       2.08G  1.15T  2.03G  -
rpool/data/vm-107-disk-0       45.0G  1.15T  32.3G  -
rpool/data/vm-107-disk-1        106G  1.15T   106G  -
rpool/data/vm-108-disk-0        105G  1.15T  90.3G  -
rpool/data/vm-108-disk-1       79.4G  1.15T  78.7G  -
```

```
vmbaks/vm-100-disk-0           12.6G   229G  9.28G  -
vmbaks/vm-101-disk-0            221G   229G   219G  -
vmbaks/vm-102-disk-0           9.25G   229G  8.92G  -
vmbaks/vm-103-disk-0           7.15G   229G  7.12G  -
vmbaks/vm-103-state-clean       990M   229G   990M  -
vmbaks/vm-106-disk-0           3.39G   229G  3.32G  -
vmbaks/vm-107-disk-0           54.2G   229G  40.3G  -
vmbaks/vm-107-disk-1            132G   229G   132G  -
vmbaks/vm-108-disk-0            128G   229G   112G  -
vmbaks/vm-108-disk-1            101G   229G   100G  -
```

and this is one of the snapshots

```
rpool/data/vm-108-disk-1@pyznap_2020-07-06_13:00:02_frequent       18.5M      -  78.7G  -


vmbaks/vm-108-disk-1@pyznap_2020-07-06_13:00:02_frequent              0B      -   100G  -
```

Thank you

**Comment by yboetz** [comment]
Do you clean up snapshots on the dest? Might be that you are retaining more snapshots on the dest that then take up more space.
Or maybe you have compression enabled on the source but not the dest.

**Comment by killmasta93** [comment]
Thanks for the reply, so the compression was disabled on the dest, so i enabled it wouldn't in theory automatically compress the data on the dest? or do i need to do something else?

`vmbaks                                                             compression  on        local
`

**Comment by yboetz** [comment]
It only compresses data after you enable compression. Data already on the dataset will not be compressed. For that you need to delete it and transfer it to the dest again.

**Comment by killmasta93** [comment]
thanks for the reply, quick question as currently i have the cron job, but not sure if its possible to add the & or after the snap because what i realized is that there both on the same hour so sometimes i an odd error

```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 * * * *   root     pyznap snap | grep 'ERROR' && mail -s "pyznap error" sistemas@myemail.com
0 * * * *   root     pyznap send | grep 'ERROR' && mail -s "pyznap error" sistemas@myemail.com
```

**Comment by yboetz** [comment]
Having them both at the same time is not advisable. Maybe have the `send` one minute later, i.e. `1 * * * *`. Or you can also combine them in one command

    { pyznap snap ; pyznap send } | grep  ....

**Comment by killmasta93** [comment]
thanks for the reply something like this?

`42 08 * * *   root     { pyznap snap ; pyznap send }  | grep 'ERROR' && mail -s "pyznap error" email@mydomain.com`

i tried it but i got this error 


`/bin/sh: 1: Syntax error: end of file unexpected (expecting "}")`

**Comment by yboetz** [comment]
Sorry, wrote it wrong, there is a `;` missing before the last curly brace. So your command has to look like this:

    42 08 * * * root { pyznap snap ; pyznap send ; } | ...
