### ISSUE TITLE
Only backup vm inside of the rpool?

### ISSUE THREAD

**Issue by killmasta93** [yboetz/pyznap#64]
Hi,
I was wondering if i have the correct config, the idea is to only backup this location 
the vm 104 disk 1
`
rpool/data/vm-104-disk-1                     16.0G  4.32T  16.0G  -
`
but when i check the dest i only see this
normally i see the vm-104-disk-1 below of the vmbaks/data

```
vmbaks                                       13.5G   885G    25K  /vmbaks
vmbaks/data                                  13.5G   885G  13.5G  -
```
This is the config

```
[rpool/data/vm-104-disk-1]
frequent = 30
snap = yes
clean = yes
dest = vmbaks/data



[vmbaks/data]
frequent = 10
clean = yes


```

Thank you

**Comment by yboetz** [comment]
This will backup the location `rpool/data/vm-104-disk-1` to `vmbaks/data`. If you want the same dataset structure as on your source you need to specify the policy as:

    [rpool/data/vm-104-disk-1]
    frequent = 30
    snap = yes
    clean = yes
    dest = vmbaks/data/vm-104-disk-1

**Comment by killmasta93** [comment]
Thanks for the reply, i tried but i get this error
```

root@prometheus:~# pyznap -v send
Jul 12 11:46:07 INFO: Starting pyznap...
Jul 12 11:46:07 INFO: Sending snapshots...
Jul 12 11:46:07 ERROR: Destination vmbaks/data/vm-104-disk-1 does not exist...
Jul 12 11:46:07 INFO: Finished successfully...

```
```
[rpool/data/vm-104-disk-1]
frequent = 30
snap = yes
clean = yes
dest = vmbaks/data/vm-104-disk-1



[vmbaks/data]
frequent = 10
clean = yes
```

**Comment by yboetz** [comment]
The (root) dataset you send to needs to exist, so you first have to do 

    zfs create vmbaks/data/vm-104-disk-1

Then you can send to that dataset. Child datasets of that one will be created, but the one you specify in your policy needs to exist.

**Comment by killmasta93** [comment]
thank you that did the trick :=)
