### ISSUE TITLE
SSH send error

### ISSUE THREAD

**Issue by ihard** [yboetz/pyznap#65]
Hi, my config
```
[zpool/data]
hourly = 24
snap = yes
clean = yes
dest = ssh:22:backup@backup-server:zpool/data
dest_keys = /home/backup/.ssh/id_rsa
compress = gzip
```
i run
```
pyznap snap
pyznap send
```
and get error
`Jul 21 18:56:40 ERROR: Error while sending to backup@backup-server:zpool/data: umount: only root can use "--types" option - cannot unmount '/backup/data': umount failed...`
is it possible to somehow get around this error by running a non-root user ?

**Comment by yboetz** [comment]
You need to login as root user on your dest, as zfs commands need root access.

**Comment by ihard** [comment]
Solved by adding sudo in this line https://github.com/yboetz/pyznap/blob/master/pyznap/pyzfs.py#L169
It would be convenient to have this as an option, thank you.

**Comment by florian-obradovic** [comment]
Same here - thx for the hint with sudo in line 169. Works for me.
