### ISSUE TITLE
[QUESTION]  Restoring backup locally from a different drive

### ISSUE THREAD

**Issue by alderson59** [yboetz/pyznap#68]
I've finally got snap and send working. Looks great! Not sure if this is covered by the tool, but let's say I have a backup of zpool1/fs1@time0, stored it in zpool2/zpool1/fs1@time0, then how can we restore the backup of zpool1/fs1@time0 to zpool1, from zpool2? Assuming zpool2 is on the same local machine as zpool1.

What are the commands to do this?

**Comment by yboetz** [comment]
You can simply send from zpool2 to zpool1 using

    pyznap send -s zpool2/zpool1/fs1 -d zpool1/fs1

This will send over the complete backup. You cannot restore a single snapshot, for that you would have to use `zfs send` directly, but you can send over everything and then rollback if you need to :).
