### ISSUE TITLE
Retry mecanism for zfs zend

### ISSUE THREAD

**Issue by maireanu** [yboetz/pyznap#69]
It is possible to add an mechanism when a snapshot is send and there is exeception, to be possible to retry and resend the snapshot.

Example: 

1. sending on snapshot , 
2. an error appear 
  - warning: cannot send 'pool/TenantName@pyznap_2020-08-28_00:00:44_daily': Broken pipe 
  - ERROR: Error while sending to root@0.0.0.0:pool/TenantName
3. retry sending the snapshot.

**Comment by yboetz** [comment]
Should be possible to add a retry loop around the `send_snap` method. I haven't really had time to work on pyznap recently though, so no promises on when I might implement this.

**Comment by Fmajor** [comment]
see #70

**Comment by maireanu** [comment]
Changes look good. I will make some tests to check it out, I will return with a reply after the tests

**Comment by Fmajor** [comment]
Hi maireanu,
#70 is colse to be merged, we need more tests, could you do it?

> Changes look good. I will make some tests to check it out, I will return with a reply after the tests

**Comment by yboetz** [comment]
The new release adds the `retries` and `retry_interval` options. You can specify how many times pyznap tries to send, and how long to wait in between tries. Thanks to Fmajor for this!
