### ISSUE TITLE
Exclude Snapshots?

### ISSUE THREAD

**Issue by killmasta93** [yboetz/pyznap#72]
Hi
I was wondering if its possible to exclude a snapshot, example i have PVE-ZYNC which sends snapshots of my proxmox vm to another proxmox host but i also have pyznap which sends to my usb disk.
The idea is to exclude all snapshots called

`@rep_`

i did see the option to exclude, but i think its only for the  dataset

`exclude = rpool/filesystem/data/* `

Thank you

**Comment by yboetz** [comment]
It's not possible to exclude snapshots, you can only exclude datasets with the `exclude` flag.

**Comment by killmasta93** [comment]
oh gotcha thanks again

**Comment by killmasta93** [comment]
quick question because i cannot exclude the snapshots is there a possible to delete all those snapshots which start with @rep 
i have this script but it deletes all the snapshots would only need to delete all snapshots on vmbaks/data
that start with @rep

```
#!/bin/bash
for snapshot in `zfs list -H -t snapshot | cut -f 1`
do
zfs destroy $snapshot
done
```

**Comment by yboetz** [comment]
How about this?
```
#!/bin/bash
for snapshot in `zfs list -H -t snapshot | grep "@rep" | cut -f 1`
do
zfs destroy $snapshot
done
```

**Comment by toddpfaff** [comment]
tip - you can also avoid the cut by doing:

zfs list -H -o name -t snapshot

**Comment by killmasta93** [comment]
so i realized that running the command also deletes all the snapshots on my rpool, possible to delete only the snapshots on my other pool called baksvms?
Thank you

**Comment by yboetz** [comment]
`zfs list -H -o name -r baksvms -t snap` ?

**Comment by killmasta93** [comment]
thank you that did the job :)
