### ISSUE TITLE
Cool use of pyznap to migrate data through tiers of storage

### ISSUE THREAD

**Issue by jpbrown-15** [yboetz/pyznap#74]
First, I want to say thank you for creating such a fantastic utility!  I've been using it for about a year and recently decided to use it to solve an IO bottleneck problem I've been having with running multiple virtual machines on my desktop system.  I thought I'd share it with you and others because it demonstrates the power and flexibility of pyznap.

My challenge was simple.  I have a desktop that had 4 HDD that supported 2 zfs mirrored pools.  Effectively, 2 drives per pool.  One pool (rpool) supported my OS, the other pool (dpool) supported all the qcow2 files for my KVM virtual machines.  The problem was, I could run 6 virtual machines at one time but they were slow.  If I added a 7th running VM, odds are that I would create a high enough IO load that programs running in some of the VMs would begin to fail.  I needed higher IO capacity.

IO capacity is simple enough to fix -- switch to SSD.  But an equivalent capacity, mirrored, to replace my HDDs is still very expensive.  Yet, I could scrape up the budget to add one SSD (2TB).  So, placing some of my virtual disks on the SSD could improve IO bandwidth but then opens me up to a component failure.  Periodic backups is certainly required.

I ran across a method that used an external snapshot of the qcow2 files and then leveraged rsync to transfer changed blocks to my mirrored dpool.  That worked, but each qcow2 file took at least 30 minutes for rsync to process.  I had placed 6 VM's on the SSD so it was taking 3 hours for one backup cycle -- hardly acceptable when you know that the total delta blocks were under 20 GB.  By the way, I began with F2FS as the file system on the SSD so there was no native snapshot, nor send/receive.

But that got me thinking, what if I switched the file system to zfs on the SSD?  Could I then leverage zfs' snapshot and send/receive?  How much faster would that be?  And could I stage the data periodically so the data flows from fast (SSD) to slower (HDD) and finally to my super slow external archive/backup?

Of course, the answer is yes, you can do all of this and it is faster -- much faster!  In fact, in testing, I was able to snapshot the SSD and transfer 2GB of changes to my internal mirrored pool in under 1 minute.  That 1 minute captured changes to all 6 of the VM's qcow2 files.  This was a change in design from transferring each file's deltas using rsync (that operates at the file level) to zfs send/receive that works at the pool/dataset level.  In fact, once I populated my initial backup from the SSD to my internal pool as the first step on the path to migrating the data to external storage, I could implement frequent snapshots and transfers to minimize the amount of data loss due to the failure of the single SSD.

After proving it out without pyznap, I then wondered how I could do this with pyznap.  Afterall, who wants to maintain multiple processes that do similar/same things?  Here's what I came up with.  I'm sure there are other ways to configure this and solve the problem, but this is my solution.

First, I established my transfer flow design.  I wanted to periodically take data from my SSD and place it on my mirrored pool.  So, it looked something like this:

ssdpool (SSD 2TB ) --> dpool (mirrored HDD 4TB) --> bkuppool (usb attached HDD 8TB)

I also wanted retain the backups I had for other pools and datasets:
rpool (mirrored HDD 2TB) --> bkuppool
dpool (mirrored HDD 4TB) --> bkuppool (dpool has 3 other datasets in addition to the ssd backup)
arcpool (mirrored HDD 2TB) --> bkuppool
bpool (mirrored HDD 1GB) --> bkuppool

I also wanted the ssdpool migration to occur every 2 hours during my primary operating time (ssdpool --> dpool) while all my other backups occur once a day.  To put them all in one config file created challenges.  I wanted to have few snapshots on my ssdpool, hold more on my dpool, and even more on my bkuppool.  But to keep things manageable, I also didn't want to create separate config files for each pool.  I've attached all my config files and scripts.

The first script (**ssd-backup.sh**) handles my frequent snapshots of the ssd and transfers the data to dpool.  It also conducts cleanup of the ssd since there is no point in retaining too many snapshots and consuming my SSD.

The second script (**zfs-backup**) is my daily backup script that takes data from my mirrored pools and sends it to external storage. 

The third script (**zfs-backup-cleanup.sh**) runs daily and conducts cleanup of my external storage to remove expired snapshots beyond my retention policy.  It also cleans up my internal storage which is comprised of 2 configuration files so that I can address differences in retention policy.

The conf files used in the various scripts are also attached.  

**pyznap-snap-send-clean-default.conf** is the largest and main conf.  It is used for snapshotting the majority of the datasets, sending them to the bkuppool external storage and cleaning up the internal storage (except part of dpool and ssdpool).

**pyznap-snap-send-clean-ssd.conf** is used to manage the ssdpool.  It is used when snapshotting the ssdpool, sending the data from the ssdpool to the dpool and cleaning up the ssd.

I then have 2 additional conf files dealing with the special dataset on dpool that holds the backup from the ssdpool:

**pyznap-dpool-ssd-bkup-send.conf** is used with sending any snapshots found in the dpool/ssd-bkup dataset (populated from the frequent sending of the ssd-backup.sh.  You will note that this conf does not snapshot anything since it is purely a staging for what will be sent to the external storage.  

**pyznap-dpool-ssd-bkup-clean.conf** is used to clean up the dpool/ssd-bkup dataset, removing any unwanted snapshots.

Finally, we have the **pyznap-clean-bkuppool.conf.**  This is used to control the retention policy and remove unwanted snapshots from the external storage.

Probably the easiest way to see how this all works together is to look at each script and then each of the conf files that the script consumes.  By breaking apart the pyznap's conf files, you can create tailored processes to refine how you want data to flow from live to backup and eventually be retired.

Thanks again for creating such a flexible and powerful utility to make zfs snapshot, send, and receive easy to use.

[pyznap-clean-bkuppool.conf.txt](https://github.com/yboetz/pyznap/files/5467837/pyznap-clean-bkuppool.conf.txt)
[pyznap-dpool-ssd-bkup-clean.conf.txt](https://github.com/yboetz/pyznap/files/5467838/pyznap-dpool-ssd-bkup-clean.conf.txt)
[pyznap-dpool-ssd-bkup-send.conf.txt](https://github.com/yboetz/pyznap/files/5467839/pyznap-dpool-ssd-bkup-send.conf.txt)
[pyznap-snap-send-clean-default.conf.txt](https://github.com/yboetz/pyznap/files/5467840/pyznap-snap-send-clean-default.conf.txt)
[pyznap-snap-send-clean-ssd.conf.txt](https://github.com/yboetz/pyznap/files/5467841/pyznap-snap-send-clean-ssd.conf.txt)
[ssd-backup.sh.txt](https://github.com/yboetz/pyznap/files/5467842/ssd-backup.sh.txt)
[zfs-backup.txt](https://github.com/yboetz/pyznap/files/5467843/zfs-backup.txt)
[zfs-backup-cleanup.sh.txt](https://github.com/yboetz/pyznap/files/5467844/zfs-backup-cleanup.sh.txt)

**Comment by yboetz** [comment]
Thanks for the feedback, really cool to hear that it works so well for you :). 

I have a similar setup, where I have ~15 LXD containers running on an SSD on my server, but without any redundancy. I then do nightly backup of this SSD to my RAIDZ1 data pool. I don't need more regular backup, since all data in the containers is mounted from the data pool anyway, so in case of SSD failure I only lose the containers themself, which I can restore from an at most 24h old backup. I also have around 3 different pyznap configs, for local and remote backup :).

Two things to note: 
- As mentioned in the other issue, you could turn off unwanted snapshots by setting
```
[rpool/ROOT/ubuntu_3chf0x]
snap = no
```
and then turn them on for child datasets.

- If I saw correctly, you only take 4 frequent snapshots and no hourly for the SSD pool, and then send every 2h to your backup location. How often do you take snapshots? It might be that after those 2h all common frequent snapshots between SSD and backup are deleted from the SSD and then it has to do incremental sync from the daily snapshot, which results in more data to transfer.

**Comment by jpbrown-15** [comment]
Thanks for the feedback.

Unfortunately, with the root on zfs layout, the rpool/ROOT/ubuntu_UUID dataset contains the actual root directory, which for me includes data not found in other datasets.  So, setting snap = no at that level would cause data loss for me.  I should really check into that and see if I can eliminate that and then turn on snap for the children individually.

As for my SSD, I used the frequent snapshot since I originally planned to snapshot every 15 minutes.  At each of those snapshot events, I also send the snapshot to my dpool/ssd-bkup.  It really doesn't matter if I snapshot then at 2 minute intervals or 2 hour intervals, the most recent snapshot is sent.  After the send, I then do the clean only on the ssd -- that keeps my frequent snapshot count to the 4 most recent.  

However, my dpool/ssd-bkup grows in the number of frequent snapshots that are delivered from the ssd backup events.  Once a day, I send the content of dpool/ssd-bkup to my external backup storage.  I happen to do this in the morning with my daily snapshot/send event.  And in the evening, I do the cleanup for both dpool (which includes the dpool/ssd-bkup) and bkuppool.  

The key for this to work is to make sure I always have enough common ancestors.  That is why I let my dpool/ssd-bkup grow with more snapshots so it can receive new snapshots from the ssd and has enough history so it can send them to my bkuppool.  

If I do increase my snapshot interval for the ssd, I'll likely increase the number I hold in dpool/ssd-bkup.  The number I increase it to will depend on how frequent I take and send snapshots so that I always have a common ancestor on my bkuppool.  So, if I enable 15 minute snapshots for a 6 hour window on my ssdpool, my ssdpool may continue to have 4 frequent snapshots but my dpool/ssd-pool may be increased from 8 to 26 (that represents a day's worth of frequent snapshots + 2 for a margin of safety).  When the daily send from dpool/ssd-bkup to bkuppool occurs, there should then be at least one, but likely 2 common ancestors along with the daily, weekly, and monthly points that I can restart/rebuild from if something goes wrong somewhere in the middle (e.g. I run out of space down stream and need to do some cleanup before sending from some point in the lineage).

**Comment by yboetz** [comment]
That makes sense. I'm just a bit paranoid about common snapshots, so I keep up to yearly snapshots on the SSD as well, since there is enough space and (apart from space) there's no cost for more snapshots :). I think on my backup I then even keep up to 5 years. But I'm happy that pyznap is as useful for you as it is for me :).
