### ISSUE TITLE
Sending Snap destination does not exist?

### ISSUE THREAD

**Issue by farzadha2** [yboetz/pyznap#75]
hello,
Currently trying to send the snapshot to my other pool but im getting this error

```
# pyznap snap
Nov 01 15:30:50 INFO: Starting pyznap...
Nov 01 15:30:50 INFO: Taking snapshots...
Nov 01 15:30:50 INFO: Taking snapshot rpool/data/vm-102-disk-1@pyznap_2020-11-01_15:30:50_frequent...
Nov 01 15:30:50 INFO: Cleaning snapshots...
Nov 01 15:30:50 INFO: Finished successfully...

# pyznap send
Nov 01 15:30:55 INFO: Starting pyznap...
Nov 01 15:30:55 INFO: Sending snapshots...
Nov 01 15:30:55 ERROR: Destination vmbaks/data/vm-102-disk-1 does not exist...
Nov 01 15:30:55 INFO: Finished successfully...

```

```
vmbaks                    80.0M  1.76T    96K  /vmbaks
vmbaks/data                 96K  1.76T    96K  /vmbaks/data

```

Thank you

**Comment by yboetz** [comment]
pyznap will not automatically create datasets that don't exist. You can force it to create datasets with the `--dest-auto-create` flag, though I think you don't have the most recent version of pyznap, since there you get the error message
```
ERROR: Destination X does not exist, manually create it or use "dest-auto-create" option...
```

**Comment by farzadha2** [comment]
Thanks for the reply, how could i update the pyznap?  whats odd is that i remember before it did it automatic if the data file did not exist, 

this is my config

```
[rpool/data/vm-102-disk-1]
frequent = 1
snap = yes
clean = yes
dest = vmbaks/data/vm-102-disk-1

[vmbaks/data]
frequent = 5
clean = yes
```

**Comment by yboetz** [comment]
How did you install it, using pip? Then you should just be able to do `pip3 install --upgrade pyznap`. 

Btw, about your config: You should always keep more than 1 snapshot on your dataset. zfs send/receive works by having common snapshots between source and destination, so if you only keep 1 snapshot and then delete the old one, there might not be any common snapshot between source and dest and then you will not be able to incrementally send over your backup.

**Comment by farzadha2** [comment]
thanks for the reply, so i updated from 1.5.0 to 1.6.0 so what would be the correct command line? to send that data set?

I tried

`pyznap send --dest-auto-create`


as for the snapshots correct i had it 30 but because something happened to my usb i was testing it with 1 because it was not transferring the data but then realized it was another issue

**Comment by yboetz** [comment]
Does that command not work? If so, then you might have to set the option in your config file, so
```
[rpool/data/vm-102-disk-1]
frequent = 1
snap = yes
clean = yes
dest = vmbaks/data/vm-102-disk-1
dest_auto_create = yes
```

**Comment by yboetz** [comment]
If you use `pyznap send` without the `-d` and `-s` option, then he will read from the config file and ignore any other flags. So the flag would only work if you use 
```
pyznap send -s rpool/data/vm-102-disk-1 -d vmbaks/data/vm-102-disk-1 --dest-auto-create
```

**Comment by farzadha2** [comment]
Thank you the above config worked flawless its currently passing the info
