### ISSUE TITLE
clean failing / configuration error ?

### ISSUE THREAD

**Issue by svennd** [yboetz/pyznap#77]
I have been running pyznap for a while with this configuration : 
```
[demo]
  frequent = 1
  hourly = 4
  daily = 3
  weekly = 3
  monthly = 3
  yearly = 0
  snap = yes
  clean = yes
  compress = lz4

[demo/brick_11]
  dest = ssh:22:root@demob:demob/brick_11
  dest_keys = /root/.ssh/id_rsa_backup
  clean = yes

[ssh:22:root@demob:demob/brick_11]
  key = /root/.ssh/id_rsa_backup
  frequent = 0
  hourly = 0
  daily = 3
  weekly = 3
  monthly = 3
  yearly = 0
  clean = yes
```
(the original file is longer as there are multiple bricks, but all have this configuration)

snapshots on the demo server : 
```
zfs list -t snapshot |wc -l
85
```

snapshots on the demo backup server : 
```
zfs list -t snapshot |wc -l
2487
```

How do I clean this up ? clearly something has broken, but I prefer not to copy everything again :)

**Comment by svennd** [comment]
Well this is not surprisingly a copy-paste error resulting in the clean part of one subvolume was gone. /not-an-issue

**Comment by yboetz** [comment]
Glad you figured it out :D
