### ISSUE TITLE
Pyznap sending zsysctl state saves

### ISSUE THREAD

**Issue by jedi-nz** [yboetz/pyznap#85]
Hi Yannick,

I have Ubuntu 21.04 installed root on zfs. I have installed pyznap and observed that pyznap is sending zsysctl state saves as well as pyznap snapshots.

`root@orac:/home/mike# pyznap snap`
`Oct 06 13:22:53 INFO: Starting pyznap...`
`Oct 06 13:22:53 INFO: Taking snapshots...`
`Oct 06 13:22:53 INFO: Taking snapshot rpool/USERDATA/mike_znt3hn/OneDrive@pyznap_2021-10-06_13:22:53_monthly...`
`Oct 06 13:22:53 INFO: Taking snapshot rpool/USERDATA/mike_znt3hn/OneDrive@pyznap_2021-10-06_13:22:53_weekly...`
`Oct 06 13:22:53 INFO: Taking snapshot rpool/USERDATA/mike_znt3hn/OneDrive@pyznap_2021-10-06_13:22:53_daily...`
`Oct 06 13:22:53 INFO: Taking snapshot rpool/USERDATA/mike_znt3hn/OneDrive@pyznap_2021-10-06_13:22:53_hourly...`
`Oct 06 13:22:53 INFO: Cleaning snapshots...`
`Oct 06 13:22:53 INFO: Finished successfully...`

`root@orac:/home/mike# pyznap send`
`Oct 06 13:27:11 INFO: Starting pyznap...`
`Oct 06 13:27:11 INFO: Sending snapshots...`
`Oct 06 13:27:12 INFO: No common snapshots on mike@mydomain.co.nz:tank/backups/onedrive, sending oldest snapshot rpool/USERDATA/mike_znt3hn/OneDrive@autozsys_fpz1i4 (~42.6K)...`
`Oct 06 13:27:13 INFO: Updating mike@mydomain.co.nz:tank/backups/onedrive with recent snapshot rpool/USERDATA/mike_znt3hn/OneDrive@pyznap_2021-10-06_13:22:53_hourly (~3.3G)...`
`  3.34GiB 0:01:01 [55.6MiB/s] [====================================================> ] 99% `
`Oct 06 13:28:30 INFO: mike@mydomain.co.nz:tank/backups/onedrive is up to date...`
`Oct 06 13:28:31 INFO: No common snapshots on mike@mail:data/Back-ups/onedrive, sending oldest snapshot rpool/USERDATA/mike_znt3hn/OneDrive@autozsys_fpz1i4 (~42.6K)...`
`Oct 06 13:28:32 INFO: Updating mike@mail:data/Back-ups/onedrive with recent snapshot rpool/USERDATA/mike_znt3hn/OneDrive@pyznap_2021-10-06_13:22:53_hourly (~3.3G)...`
`3.34GiB 0:01:07 [50.9MiB/s] [====================================================> ] 99% `
`Oct 06 13:30:00 INFO: mike@mail:data/Back-ups/onedrive is up to date...`
`Oct 06 13:30:00 INFO: Finished successfully...`

I did not observe this behaviour with Ubuntu 20.04 root on zfs. Do you have any info on this?

Thanks.

**Comment by yboetz** [comment]
zsysctl state saves are normal zfs snapshots, and `pyznap send` sends all snapshot from source to dest, not only pyznap snapshots. That is by design, since I wanted `pyznap send` to do full replication. 

Did you use zsysctl on Ubuntu 20.04 root on zfs? If so I would expect the same behaviour there as well.

**Comment by jedi-nz** [comment]
Yes I had Ubuntu 20.04 on root but pyznap was only sending pyznap snapshots. I think this may have been due to a revert that I did that didn't go correctly. Subsequent reverts were not working. That was why I ending up doing a reinstall. May I suggest incorporating an ability to deactivate this functionality in your next release. I will end up with a whole lot of snapshots I don't need/want.

Thank you for your reply.

**Comment by yboetz** [comment]
That will not be so easy to incorporate, since pyznap does not send single snapshots. It only searches for most recent common and newest snapshots, then uses the zfs send `-R -I` option to automatically send all snapshots inbetween.  There it cannot discern between pyznap snapshots and others. Making it so that pyznap only sends pyznap snapshots would need some work and refactoring there, and I don't plan to do that atm.

**Comment by jedi-nz** [comment]
Hi Yannick,

I know nothing about programming but would it be difficult to set a user property on all pyznap snapshots:

`zfs set pyznap:flag=yes pool/dataset@pyznap`

Then a user could have in their config:

`pyznap:flag = yes`

Then when pyznap searches for snapshots it could limit the search to snapshots with that property being set.

Would that be hard to do?

**Comment by yboetz** [comment]
Knowing which snapshots belong to pyznap is not hard, but the way sending is implemented now there is no way to filter out snapshots, since most of it is handled by `zfs send` itself. Changing that would require quite a bit of work.

**Comment by jedi-nz** [comment]
Hi Yannick,

Do you know what is happening here?

`root@orac:~# ssh mike@mydomain.co.nz`
`Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-88-generic x86_64)`

`1 update can be applied immediately.`
`To see these additional updates run: apt list --upgradable`

`Last login: Thu Oct 14 19:44:38 2021 from 210.54.xx.xx`
`mike@ubuntuzfs:~$ exit`
`logout`
`Connection to mydomain.co.nz closed.`
`root@orac:~# pyznap send`
`Oct 14 19:50:49 INFO: Starting pyznap...`
`Oct 14 19:50:49 INFO: Sending snapshots...`
`Oct 14 19:52:23 ERROR: Error while checking 'zfs receive' on mike@mydomain.co.nz:tank/backups/business-computer:` `'Command '['ssh', '-i', '/root/.ssh/id_rsa', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1m', '-o', 'ControlPath=/tmp/pyznap_mike@mydomain.co.nz:22_2021-10-14_19:50:49', '-p', '22', '-o', 'ServerAliveInterval=30',` `'mike@mydomain.co.nz', 'ps', '-Ao', 'args=']' timed out after 5 seconds'...`
`Oct 14 19:52:23 INFO: mike@mail:data/Business-computer is up to date...`
`Oct 14 19:52:23 INFO: Finished successfully...`

This is my config:

`[storage/Back-ups/Business-computer]`

`daily = 3`
`snap = yes`
`clean = yes`
`dest_auto_create = yes`
`resume = yes, yes`
`retries = 10, 10`
`retry_interval = 3600, 3600`
`dest = ssh::mike@mydomain.co.nz:tank/backups/business-computer, ssh::mike@mail:data/Business-computer`

`ssh::mike@mydomain.co.nz:tank/backups/business-computer]`

`daily = 3`
`clean = yes`

Sending computer is Ubuntu 21.04. I have not made any changes, it was working perfectly.

**Comment by yboetz** [comment]
Does it happen every time now, or was it a one time error?

**Comment by jedi-nz** [comment]
Seems to be working fine now. If you could suggest any log files I could look at to try and figure out what the problem was that would be appreciated.

**Comment by yboetz** [comment]
I'm really not sure, could be many things, maybe just a short connection issue. If it doesn't happen again then it should be ok :).
