### ISSUE TITLE
Suggestion: implement WOL

### ISSUE THREAD

**Issue by stephanGarland** [yboetz/pyznap#86]
Is there any desire to have WOL logic for send? I have a separate node that I wake up daily to send snapshots to. It's cantankerous and doesn't always like to see its boot drive right away, so it takes a few cycles to actually boot. As such, I wrote a Python script that uses [ipmipower](https://linux.die.net/man/8/ipmipower) to cycle power until the VM responds on port 22.

I could adapt it more generically (hopefully, most people's servers aren't that horrific) and make a PR.

**Comment by yboetz** [comment]
Hi Stephan

Thanks for the suggestion. While such a script is certainly useful, it is out of the scope of pyznap. I'd like to keep it simple and focus on the zfs aspects (snapshot rotation & send), nothing else. As such wont add any WOL functionality to pyznap.
