### ISSUE TITLE
`pyznap send` on encrypted pool produces multiple issues: ignoring `--exclude`, breaks `mbuffer`, ...

### ISSUE THREAD

**Issue by se-jaeger** [yboetz/pyznap#87]
Hi,

I want to send my encrypted `datapool` to a `backuppool`, which is an USB drive.
The backuppool is created as follows (settings are copied from datapool creation script. I already tested without those.):
```
zpool create -o ashift=12 -O acltype=posixacl -O compression=zstd -O normalization=formD -O relatime=on -O dnodesize=auto -O xattr=sa backuppool /dev/disk/by-id/<USB drive>
```
For this I'm using pyznap:
```
pyznap send \
  --source "datapool" \
  --dest "backuppool/homeserver" \
  --exclude "datapool/dataset1" "datapool/dataset2" \
  --raw \
  --dest-auto-create
```

**Unfortunately I encountered some issues and errors.**

1. `--exclude` is ignored at all. Nothings changes if I add, e.g., `"datapool/dataset1/*"` to ignore all subsequent datasets
2. for all top level datasets, e.g., `datapool/anexample`, I get the following error (child datasets work as expected, e.g.: `datapool/anexample/test`):
```
ERROR: Error while sending to backuppool/homeserver/anexample: cannot receive new filesystem stream: zfs receive -F cannot be used to destroy an encrypted filesystem or overwrite an unencrypted one with an encrypted one...
```
3. Sometimes `mbuffer` fails:
```
mbuffer: error: outputThread: error writing to <stdout> at offset 0x60000: Broken pipe
mbuffer: warning: error during output to <stdout>: Broken pipe
```

**What I tried to get it running properly (without success).**

- Don't use `--exclude`, instead run pyznap multiple times for each `datapool/dataset` I want to send
- use `--resume`
- create backupool without setting any properties: `zpool create backuppool /dev/disk/by-id/<USB drive>`
- remove the intermediate dataset on the backuppol: `--dest "backuppool"`

Any ideas what's wrong or how I can solve my issues? I'm very happy to help!
Thank's in advance.

**Comment by yboetz** [comment]
Hi

This seems to be a limitation of `zfs send/receive` with encrypted datasets: https://github.com/openzfs/zfs/issues/6793

It seems that with encrypted datasets you cannot use the `-F` flag, though that is needed in pyznap for incremental updates.  I'm not sure how to work around this with pyznap atm. 

The `mbuffer` errors is related, if the receive fails then `mbuffer` also shows an error.

`--exclude` works for me for non-encrypted datasets. Note that `datapool/dataset1/*` will not ignore `datapool/dataset1` itself, only its child datasets.

**Comment by se-jaeger** [comment]
Thanks for your answer!

I'm not sure if I understand when `-F` is valid but that's related to ZFS and not `pyznap`.
Let me dig into the code and check whether I can understand the issue properly and find a solution.

At least we can ignore the `mbuffer` error.

I use `pyznap` to backup my `rpool` regularly to `datapool`, both are encrypted. `--exclude` works as expected. Do you think the reason here could be that the target (datapool) is decrypted? When sending to a backuppool it's encrypted.

**Comment by yboetz** [comment]
Yes I think that is the reason. The problem from the `-F` flag arises from the target dataset being encrypted, so if your `datapool` is not encrypted then I guess everything works as it normally would.

**Comment by se-jaeger** [comment]
Implemented a simple ZFS only script to create offsite backups.

Since this is no really pyznap issue, I suggest to close this one.
